### ISSUE TITLE
Allow functions everywhere

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#102]
- [x]  Properties
- [ ]  Pseudo
    - [x] Attribute
    - [ ] Nth-child
    - [x] Not
- [x]  Nested functions

By my count, the functions are almost available naturally everywhere

**Comment by solleer** [comment]
What if we had the pseudo matcher parse the tokens in brackets by default
I can't think of a use case where something other than inside the brackets would be parsed

**Comment by hobbeshunter** [comment]
It also seems that functions aren't working inside conditionals like
```
#id:data[func() = 1]
```

**Comment by solleer** [comment]
Try removing the spaces around the equals sign

**Comment by TomBZombie** [comment]
if that does fix it, making the parser ignore spaces should be fairly simple

**Comment by hobbeshunter** [comment]
No, I'm sorry. To be more accurate, this is my concrete problem:
```
#id:data[func().published=1]:attr(checked) {...
```

**Comment by solleer** [comment]
Does `#id:[data(func().published)=1]:attr(checked) {...` work

**Comment by solleer** [comment]
I think the problem now is that the attr pseudo doesn't set autolookup to be true when it needs to be

**Comment by solleer** [comment]
This test fails
```php
public function testFunctionCallAsConditonal3() {

	$xml = '<div></div>';

	$obj = new Foo();

	$tss = 'div:data[returnOne()=1] {content: "test" }';

	$template = new \Transphporm\Builder($xml, $tss);

	$this->assertEquals($this->stripTabs($template->output($obj)->body), $this->stripTabs('<div>test</div>'));
}
```

This test passes
```php
public function testFunctionCallAsConditonal4() {

	$xml = '<div></div>';

	$obj = new Foo();

	$tss = 'div:[data(returnOne())=1] {content: "test" }';

	$template = new \Transphporm\Builder($xml, $tss);

	$this->assertEquals($this->stripTabs($template->output($obj)->body), $this->stripTabs('<div>test</div>'));
}
```
I am almost certain the problem is that the attr pseudo doesn't set autolookup to be true when it needs to be
Also for those tests I added a function that returns `1` to the object
