### ISSUE TITLE
CssToXpath bug with cache

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#103]
I started to use caching and now I get this error

> Notice: Undefined index: 00000000458f9ec0000000007e5a80f8 in C:\Users\Solle\OneDrive\Documents\Programing Stuff\Web development\serverRoot\elemukulek\lib\Transphporm\Parser\CssToXpath.php on line 49

**Comment by solleer** [comment]
It has to do with @import

**Comment by solleer** [comment]
So here is what I have found
- When using @import the imported file is not parsed when changed unless the file importing it is changed
- When caching, the queries that are saved reference previous Csstoxpath objects not the current ones in the instance array

**Comment by solleer** [comment]
This test fails
```php
public function testCacheWithAttribute() {
	$xml = $this->makeXml('<div>
		<span data-hide="1">Test1</span>
		<span data-hide="2">Test2</span>
		</div>');

	$tss = $this->makeTss('
		span {display: block; }
		span[data-hide=data(show)] { display:none; }');

	$cache = new \ArrayObject();

	$template = new \Transphporm\Builder($xml, $tss);
	$template->setCache($cache);

	$expectedOutput = $this->stripTabs('<div><span data-hide="2">Test2</span></div>');
	$this->assertEquals($this->stripTabs($template->output(['hide' => 1])->body), $expectedOutput);

	$template = new \Transphporm\Builder($xml, $tss);
	$template->setCache($cache);

	$expectedOutput = $this->stripTabs('<div><span data-hide="1">Test1</span></div>');

	// Run output again
	$this->assertEquals($this->stripTabs($template->output(['hide' => 2])->body), $expectedOutput);
}
```

**Comment by TomBZombie** [comment]
Hmm, the @import problem will take a little work as somehow the cache will need to know the paths to all the files that have been loaded. The same thing probably needs to happen to `template()` as well.

**Comment by solleer** [comment]
Having the imported files parsed and run separately would allow the template issue in #98

**Comment by TomBZombie** [comment]
There's a few problems with that. Both the parent tss and the imported TSS must run on the same document. That can be overcome, but the biggest issue is the ordering:

```php
ul li { repeat: data(bar); }
@import 'foo.css';
```

If `foo.css` contains:

```
ul {bind: data(foo); }
ul li a {content:iteration(link); } 
```

Then this rule should run first. Currently because the rules from the imported sheet are merged with the rules from the parent sheet, they can be sorted correctly, if the imported sheet was run separately it would either have to run all the rules before or after the parent sheet's, causing a problem above where the rules should be processed in this order:

```php
ul {bind: data(foo); } //child sheet
ul li { repeat: data(bar); } //parent sheet
ul li a {content:iteration(link); }  //child sheet

```

This also causes problems with `data()` lookups because there are now two `data()` references and two sets of elements.

**Comment by solleer** [comment]
Could behavior be changed to not sort them and just interpret them in order

**Comment by TomBZombie** [comment]
There are a few reasons not to do this. 

1. It goes against CSS making transphorm harder to learn for people who know CSS
2. It will break BC
3. Generally speaking it's nice to put all `@import` statements at the top of the file so you can quickly see the dependencies, which causes problems highlighted here https://github.com/Level-2/Transphporm/issues/5#issuecomment-142116401  This allows you to override rules in the imported CSS. You'd have to be very careful where your `@import` statements were in the file to do this (you'd have to bind the data to the form before import, then import, then override any rules you wanted to).

I'd prefer to follow CSS and have rules applied in order of precedence so `ul.myClass` always takes precedence over `ul` regardless of position in the file.

**Comment by solleer** [comment]
So could every rule be attached to a file instead and it changes the basedir depending on the file

**Comment by TomBZombie** [comment]
I think the only way to solve this is to have `@import` processed in `Builder` rather than `Sheet`, however, this would mean all imports happen before/after the rules in the sheet, which may introduce precedence bugs when the parent or child apply rules to the same selector.

Alternatively, the cache could be completely wiped if any of its tracked files are changed... but this could be slow as stating every file could be quite a few files on larger projects.

**Comment by solleer** [comment]
What about passing the cache to Sheet

**Comment by solleer** [comment]
Also in the debug-exception branch I have the file passed to Sheet instead of the baseDir. That idea might help. The parse function could also return a list of imports which are then iterated over to test for differences and if there are then just that file is reparsed.

**Comment by solleer** [comment]
I think the imports should be still handled in Sheet because later it could be refactored into its own class with an interface for those instructions.

**Comment by solleer** [comment]
What if the sheet and template used the cache instead of the builder

**Comment by solleer** [comment]
What if we have a File class that handles all things with files and caching and that object is passed to sheet

**Comment by solleer** [comment]
@TomBZombie So what do you think? I'm thinking that the caching should be moved into sheet instead of the builder.

**Comment by solleer** [comment]
@TomBZombie I can work on this but I need to know what direction to take it. Mainly where it will do the caching.

**Comment by TomBZombie** [comment]
Yes, put caching in `sheet` as I think that's the best overall approach.

**Comment by TomBZombie** [comment]
After parsing the file, we'll also need to keep a list of other files included with `@import` as part of the cache and then checked as part of the cache refresh check.


Essentially:

- Load all rules form all files into the cache as it does now
- Also cache a list of files this represents
- Check all of the files to see whether the cache has been invalidated

This will be marginally slower as it will need to `stat` more files but it's a necessary fix.

**Comment by TomBZombie** [comment]
I've fixed this, but let's keep all cache discussion in #109
