### ISSUE TITLE
Splat operator not available in php 5.4

### ISSUE THREAD

**Issue by tontof** [Level-2/Transphporm#11]
The splat operator is not available in php 5.4
http://php.net/manual/en/migration56.new-features.php

It's used in function ```processFormat```, you need to remove it or to change the composer.json requirements

**Comment by TomBZombie** [comment]
Thanks for pointing this out, I'll remove it. However, it's worth noting that PHP5.4 is now end of life and no longer supported. See: http://php.net/eol.php

**Comment by tontof** [comment]
That's right, but the usage are sadly different:
http://w3techs.com/technologies/details/pl-php/5/all ;-)

**Comment by smolinari** [comment]
Just because 5.4 is being used, doesn't mean new developments like Transphporm should be keeping 5.4 as a minimum requirement. 5.6 or better is a must!

Scott

**Comment by tontof** [comment]
The problem was not about the PHP version, but with the composer.json information correspondance.

Anyway, I don't know exactly why but I also have a problem with
https://github.com/Level-2/Transphporm/blob/9a62ef4b242f3ac81dfa78646c2e04e3d776b540/src/Template.php#L20
using PHP 5.4.42 no problem with PHP 5.5.9
```Parse error: syntax error, unexpected 'list' (T_LIST)```

**Comment by smolinari** [comment]
Then why the reply about the PHP5.4 usage? I agree, the minimum version in the composer.json should be 5.6.

Scott

**Comment by tontof** [comment]
Because originally there was 2 solutions for this issue:
- remove the splat operator
- correct the composer.json

But if you read the https://github.com/Level-2/Transphporm/issues/11#issuecomment-148713797 answer from @TomBZombie , it seems to be the first one which was selected...

Maybe I'm wrong and I misunderstood his reply but anyway I let @TomBZombie decide how to correct. I just inform him that there is an other problem with PHP 5.4 (that's why I did not open a new issue).

**Comment by tontof** [comment]
I know why ```list``` does not work in for loop, it was added in PHP 5.5
http://php.net/manual/en/control-structures.foreach.php#control-structures.foreach.list

**Comment by smolinari** [comment]
Yeah, so @TomBZombie, please change the minimum version to 5.6. :smile: 

Scott

**Comment by TomBZombie** [comment]
I think that libraries should support versions of PHP that are officially supported, which at the moment means 5.5... and removing the splat operator but keeping foreach (list() )

**Comment by smolinari** [comment]
It is your project. :smile: Though, how long do you think it will take, before this project is at 1.0.0?

Scott

**Comment by TomBZombie** [comment]
It's pretty much there, I'm just working on completing a full application with it. Unfortunately I'm rather busy at the moment so it's slow progress.

Is there anything else you think needs to be added now we have nested functions, formatters and locales?

**Comment by tontof** [comment]
Maybe 2 suggestions:
- I was wondering if you think it's possible to have, using functions/formatters, the possibility to add raw content (with html tag inside) ?
It can be useful using for example a tss file for atom/rss where the entry content is often previously generated html code.
- It seems to fail when using xml output using xml namespace.
With this xml:
```
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Example Feed</title>
</feed>
```
This tss fails:
```
feed > title { content: data(title); }
```

**Comment by TomBZombie** [comment]
I'm not sure I understand your first point. Can you give an example of how you think it could work?

I'll play around with namespaces, there's no reason that shouldn't work but it may mean adjusting the way the XPath expressions is built. I've not used XPath with namespaces before so I'm not quite sure how it works. Out of interest, if you remove the xmlns attribute does the above work?

**Comment by tontof** [comment]
For the first point, 
Suppose you have html content into a variable:
```
$feed = new stdclass;
$feed->link = 'http://example.com';
$feed->content = '<h1>Title</h1><p>paragraph</p>';
```
It would be great to be able to use data with that content. (For now it transforms with ```&gt;```, ```&lt;```).

For the second point, without xmlns it works !

**Comment by TomBZombie** [comment]
I've added support for XMLNS. I'm not sure it will work in more complex scenarios where there are multiple namespaces, or actual prefixes e.g. `<xsl:foo>` but now setting the `xmlns` attribute will work correctly.

**Comment by tontof** [comment]
It does not work with my previous example:
```
$xml = '
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Example Feed</title>
</feed>
';

$tss = '
feed > title { content: "Title"; }
';


$template = new \Transphporm\Builder($xml, $tss);

echo $template->output()->body;
```
Don't know if it should work or not...

- PHP 5.5.9
- DOM/XML API Version => 20031129
- libxml2 Version => 2.9.1

**Comment by TomBZombie** [comment]
ah, I think it's the > operator. If you use just 


```php
 title { content: "Title"; }
```

It should work, I think I need to add the element prefix for this as well.

**Comment by TomBZombie** [comment]
Apologies, yes, there is a small caveat with xmlns. It will currently only work with external xml files.

Because internal XML files can be fragments, e.g. 


```
<div>
</div>
<span>
</span>
```

And an XML file must have a root element, it automatically wraps `<template>` tags around the XML which obviously doesn't have the xmlns attribute.

If you use an external xml/tss file it should work as expected. I will try to add a workaround for this, but it may not be simple

**Comment by tontof** [comment]
You're right, it works great with external files! (it also works with the ```>```!)

**Comment by TomBZombie** [comment]
I've just added `format: html` which will take a string and import it into the document. There are a couple of limitations at the moment:

1. it has to be valid XML syntax
2. It has to have a root element

**Comment by tontof** [comment]
Great, it works on a small example I've tried.

I was surprised but it also works on a more complex example without using ```format: html``` instruction. It was inside an iteration. I will try to simplify it to extract relevant source code.

**Comment by TomBZombie** [comment]
If you're using `content: data(foo)` and `data(foo)` resolves to a DomElement, it will be imported. It shouldn't automatically convert strings though.

**Comment by tontof** [comment]
Quick check and it's a string :-)

I will check tomorrow and let you know. (I will try to find a xml/tss example to illustrate)

**Comment by tontof** [comment]
Oups, I was wrong. As I needed html raw before ```format:html``` I was using ```htmlspecialchars_decode```.
Everything works as expected. I guess you can close this issue ?

**Comment by TomBZombie** [comment]
There's still a couple of tweaks that need to be made to the way HTML import works but I'll close this for now.
