### ISSUE TITLE
Format html potential bug

### ISSUE THREAD

**Issue by Mr-Chimp** [Level-2/Transphporm#122]
Hi, I am using Transphporm to output a HTML form, the form itself gets built dynamically in PHP. It was all working great until I added the keyword required to an input element at which point I just got blank output. See example below.
`<input type="text" autocomplete="off" value="" class="form-control test linuxAwesome" id="first-name" data-name="test" required name="first-name">`

I ended up changing it so that using required="" which caused it to work and start displaying the form again, my guess is this is related to the loadXml or loadHTML functions mentioned in #66

This is the working input: `<input type="text" autocomplete="off" value="" class="form-control test linuxAwesome" id="first-name" data-name="test" required="" name="first-name">`

Just thought I would mention it as it had me stumped for a good while.

**Comment by solleer** [comment]
@TomBZombie Do you think that the template function should be allowed to accept raw html and then we make the html format use the template function to allow BC?

**Comment by TomBZombie** [comment]
ideally we should used HTML, but loadHTML causes a few odd effects with partials. DomDocument will automatically wrap `<html>` and `<body>` tags, so we'd need to account for those.

**Comment by solleer** [comment]
Doesn't `template` account for those

**Comment by TomBZombie** [comment]
Actually yes, you're right this should be fine. @Mr-Chimp , can you provide the TSS and XML you used?
