### ISSUE TITLE
Standardize the coding style?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#123]
Would there be any support for the idea of using a defined set of coding style standards for Transphporm?  

I would like to highly recommend using PSR-1 and PSR-2, which are flexible enough in places where personal style doesn't have as much impact cognitive friction when reading code, but yet add enough consistency so as to make doing so easier for others.

There are a number of nice tools which make this easier, such as PHP Code Sniffer and IDEs like PhpStorm.

If there is interest, I would be happy to do the lion's share of updating existing code to be consistent.

**Comment by solleer** [comment]
Based on http://www.php-fig.org/psr/psr-1/ it seems to be following it

**Comment by cxj** [comment]
Running:

```
php-cs-fixer fix . -v --level=psr2 --dry-run
```

Suggests numerous fixes to 47 different files.

https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by TomBZombie** [comment]
PSR-2 is annoyingly inconsistent. The coding style in transphorm is mostly consistent with itself and doesn't need to be consistent with anything else.

PSR-2 does this:

```php
public function()
 {

}
``

and

```php
if () { 

}
```

...why?

**Comment by cxj** [comment]
As far as the parenthesis placement for functions, methods and classes than for `if` and other control statements, I'm sure there are arguments which can be made one way or the other.  However, the main benefit is to pick a style that is in common  and widespread use.  This particular parenthesis placement meets those criteria.  PHP is C-like, and that style has been used for C coding standards for decades.  Maybe that just means it's historical precedent.  But then, if that's what most programmers eyes are used to seeing, then the benefit of reduced effort to understand the code has been reached.

PSR-1 and PSR-2 seem reasonable and the least-instrusive standards I've seen, and are very widely used.

But hey, it's your project.
