### ISSUE TITLE
Problem with ; in content

### ISSUE THREAD

**Issue by tontof** [Level-2/Transphporm#13]
I've got an error when trying to print a ```;``` inside content.
```
PHP Notice:  Uninitialized string offset: -1 in transphporm.php on line 629
```
For example:
```
$tss = '
  h1 { content: ";"; }
';
```
Don't know if it's possible to perform this as ```;``` is the end delimiter, maybe with a  ```\```
For now I use a variable instead to print this.

**Comment by TomBZombie** [comment]
Thanks for pointing this out, yes it's to do with the fact that ;'s inside strings are not ignored by the parser. I will add a fix for this shortly.

**Comment by tontof** [comment]
Oups, I've just realized that the error on my first post will not be usefull.
Don't know if it can help you, but the line is here:
```
https://github.com/Level-2/Transphporm/blob/9a62ef4b242f3ac81dfa78646c2e04e3d776b540/src/Hook/Rule.php#L56
```

**Comment by TomBZombie** [comment]
I've fixed this and it should be futureproof, any character which has special meaning to the parser will be ignored. It now moves all strings into a string table and removes them from the TSS prior to parsing the file.

**Comment by tontof** [comment]
Thanks it works great !
