### ISSUE TITLE
Release 1.1 is not on Packagist

### ISSUE THREAD

**Issue by garrettw** [Level-2/Transphporm#130]
Not sure what the issue is, but somehow the 'v1.1' tag doesn't show up on Packagist as a release.

[edit] Oh, I just realized what the problem is. I think I've mentioned a similar problem to you before (maybe on Dice? I don't recall).
You'll want to remove the "version" line from your composer.json. :wink:

**Comment by garrettw** [comment]
Oh, I just realized what the problem is. I think I've mentioned a similar problem to you before (maybe on Dice? I don't recall).
You'll want to remove the "version" line from your composer.json. :wink:

**Comment by TomBZombie** [comment]
thanks for pointing this out, I've had to draft 1.1.1 to make this appear but it's now on packagist correctly.
