### ISSUE TITLE
Best practice for shared templates

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#131]
This issue is to ask for some feedback on preferred or intended methods for sharing templates between multiple web sites.

I have 3 web applications which share View\* (in Model-View-Controller terminology) classes which use Transphporm for generating web page output.  They also share a bunch of general purpose templates, e.g. for login, base HTML, etc.  There are then also templates which are unique to each application.

My directory structure is something like:

```
./path/to/shared/templates
./path/to/local/templates
```

That is, the 2 groups of templates are in their own directories with different paths.

My View class has no trouble finding the templates it needs.  The difficulty comes in when, for example, I want to use all shared templates and TSS files for a given page _except_ have a custom navigation menu bar at the top.  The navigation pieces are in a local unique template.

I'd like to find a way to avoid hard-coding into my generic, shared templates the unique path to the local template.  That is, I do _not_ want to do this in `shared.tss` for example:

``` css
body nav {
    content: template("/some/path/to/local/templates/navigation.xml");
}
```

Or:

``` css
body nav {
    content: template("../../../../templates/navigation.xml");
}
```

Both of the above _will_ work correctly, but as one might imagine, are very fragile and hard to maintain.

What's a proper way to approach this problem?  

Idea:  Is there some way to set a base directory for `content: template(...)` and `@import "..."` paths, so that all references could be from a known starting point provided from outside the template files themselves?  If not, would that be a sensible feature to add?  I'm thinking something like this:

``` php
$tpl = new Transphporm\Builder($xmlFile, $tssFile);
$tpl->setBasePath($path);                        // suggested new feature
return $tpl->output($data)->body;
```

**Comment by cxj** [comment]
View* -- in case you're curious, I'm not actually using MVC, but rather [ADR](https://github.com/pmjones/adr), so it's my abstract HTML Responder class which instantiates Transphporm for all HTML output.  :-)

**Comment by TomBZombie** [comment]
Perhaps we could do as CSS sort of does and use `/` to mean `cwd` of the running script. The only issue this would cause is that you couldn't load files outside the script's basedir so if you run `/var/www/foo.php` which loads transphporm, in Transphporm `/whatever/` will always be relative to `/var/www/vhosts/site.com/` and resolve to `/var/www/vhosts/site.com.whatever/` Obviously this would break loading files like `/var/www/vhosts/othersite.com/x.xml` or files elsewhere in the filesystem.

*but* since  we would hope that a website is chrooted anyway this should not be a problem in the real world.

**Comment by solleer** [comment]
I think that the `getBaseDir` function of Config should become `getFilePath` where it accepts a file path as an arg then if that path plus the baseDir in't a file then it tries cwd() plus the path

**Comment by solleer** [comment]
What function should be used to get the root since `getcwd()` might not always be the root

**Comment by TomBZombie** [comment]
I think the only sane way to handle it is to make `/` getcwd() and anything else relative to where the base PHP script is stored. I think anything else would be confusing, unless we want to allow setting the base dir like HTML's `<base>` tag

**Comment by solleer** [comment]
We could have prefixing it with `/` mean `getcwd()` and if they set the baseDir then anything prefixed with `/` will use that

**Comment by TomBZombie** [comment]
Would that cause an issue with included templates? The baseDir gets set automatically in template() calls (and possibly @import), if we have `/` meaning baseDir then `/` and `./` would resolve to the same place I think `/` needs to be consistent among all included files `@imported` TSS and templates via `template()`

**Comment by solleer** [comment]
So I will update everything to use this function
```php
public function getFilePath($filePath) {
	if ($filePath[0] == "/") return getcwd() . $filePath;
	else return $this->baseDir . $filePath;
}
```

**Comment by TomBZombie** [comment]
I have seen occasional issues in the past where odd scripts change the CWD at arbitrary points. I'd read it once in the constructor and then store it in a class variable. 

For example. in the past I've had problems with autoloaders where the cwd is changed between including one file and the next by an arbitrary script (yet another example of global state being bad!). I don't expect this to happen between creating an instance of builder and calling output but you never know.

**Comment by solleer** [comment]
Also I have that function in the Config and I'm probably going to move it to its own class.

**Comment by cxj** [comment]
Sorry for being absent from this conversation.  I got pulled off into other things the past week or so.

My **current** directory structure is based off a typical Composer project, and outlined below. 
```
.
|-- src/
|-- local-templates/
|-- shared-templates/
|-- vendor/
|   |-- composer/
|   |-- level-2/
|   `-- zendframework/
`-- web/
    |-- css/
    |-- index.php
    `-- js/
```

The _DocumentRoot_ (e.g. Apache web server) of the deployed copy points at the `./web/` directory, and `index.php` is the source code file which always gets executed and does the bootstrapping.  Source code specific to this project is in the `./src` directory, while shared source is of course in `./vendor`.  

The template directories are outside the DocumentRoot, meaning there is no URL that can be requested of the web server which will cause them to be returned to the browser client directly.  

Likewise, all of the PHP code except `index.php` is outside the DocumentRoot.

The PHP code itself must determine where to find all of the files outside the DocumentRoot.  This is straightforward enough for all of the PHP source code, as the first thing `index.php` does is include Composer's autoloader.

When my PHP code calls Transphporm, it clearly must correctly provide the appropriate path or paths.  The problem arises when, for example, a local template itself wants to include a shared template, or vice versa.  

Moreover, I'm also using a 2 stage templating process, where I construct the page's unique data in one call to Transphporm, and then use that returned partial to fill in the `<main>` section of a full _base_ page in another call to Transphporm.  That is, the _base_ page template contains the `doctype`, and HTML `<head>` and `<body>` elements, as well as HTML common to every page using this scheme, e.g. a displayable header and footer, navigation menu, etc.

While I do have my system working, I am not at all sure it is a proper way to use Transphporm!  Perhaps there is a better way to compose pages of multiple partials, and multiple local and shared templates.

Thanks for all the work you 2 are doing!  I _far_ prefer using Transphporm over the several other templating systems I've tried.

**Comment by cxj** [comment]
Regarding PHP code which changes `cwd` on the fly -- I'd say any problems or complications are on the writer of that code.  That sounds like a terrible practice in general for web code.

**Comment by solleer** [comment]
Would this change to the way file paths work help you?

**Comment by cxj** [comment]
I'm not sure I fully understand what the proposed change will do.  So it's difficult to answer your question on whether it will help me or not.

My suggestion of something like:
```php
$tpl->setBasePath($path);
```
Was very much similar to how the HTML `<base>` tag works.  

That is, if a caller did not call this new method, everything would work exactly as it does today.  If the base path were changed via such an explicit call, then I'd expect`template()` and `@import` calls to both be relative to that new base path.  

For example, if my directory structure looked like this, and was deployed to my web server at path `/site/base/path`:
```
.
|-- src/
|-- templates/
|   |-- local/
|   `-- shared/
|-- vendor/
|   |-- composer/
|   |-- level-2/
|   `-- zendframework/
`-- web/
```

I could call it this way:
```php
$tpl->setBasePath('/site/base/path/templates');
```
Then I could find any referenced templates relative to the newly-specified base (or parent), like this:
```css
@import "shared/navigation.tss";

body nav {
    content: template("shared/navigation.xml");
}
body main {
    content: template("local/content.xml");
}
```

**Comment by solleer** [comment]
Would the templates and imports in an import be relative to the imported file or the set base path

**Comment by solleer** [comment]
What if it becomes a tss operation like `@includePath`
Using your example, it would be
```css
@includePath "/site/base/path/templates";

@import "shared/navigation.tss";

body nav {
    content: template("shared/navigation.xml");
}
body main {
    content: template("local/content.xml");
}
```

**Comment by solleer** [comment]
Doing that would achieve the same effect but avoid issues with php code messing with the tss

**Comment by cxj** [comment]
I think the clearest solution (following the KISS principle) is to have all template path and import path references be relative to the same set base path.

I would prefer to inject the base path via a PHP call to a Transphporm method, rather than set it via a TSS `@includePath` directive.   My reason is that it's much easier for the PHP code to know where it is really located (real path or absolute path from root).  PHP can do that dynamically at run time, if needed.  

The path in an `@includePath` directive would effectively be hard-coded, and could not be easily relocated at deployment time.

In my environment, we have development sandboxes, a staging "final system test" system, and then production systems.  Each of these deployment hosts might have differing path names to where the templates and TSS files are ultimately located.  Also, those paths are up to IT (system admin) discretion as they manage their network of hardware and VMs, while the coding is up to development staff.  So it's good when paths can be determined at run time, either by the PHP code figuring out where it is located itself, or by reading from agreed upon config file locations.

**Comment by TomBZombie** [comment]
The problem with that its it's still inflexible, if you move the site to a different server or directory then you have to go through and adjust `@includePath` everywhere. Ideally we should have something relative to the cwd as then copying files between servers or moving them around still works. 

If we're doing that we may as well just have: 
```@import data(basePath) + "shared/navigation.tss";
```

We need "./" to be the same folder as the current file as it is at the moment. So when a file is loaded (template, tss) it loads other files relative to where it is, this makes sense and is how CSS works, how we set the base path I'm not sure.. but there's no reason that you can't use a template variable 

```
 content: template(data(documentRoot) + "shared/navigation.xml");
```

**Comment by TomBZombie** [comment]
To clarify my earlier suggestion, I'd make `/` relative to a document root of some kind. Whether that's from `getcwd()` or some variable set on the `builder` object doesn't really matter but that would let you use `./file.xml` to load a file in the same directory as a tss or `/file.xml` to load a file relative to the document root. So perhaps we just need a `$documentRoot` variable which defaults to getcwd() but can be overridden with a custom path which is then used for any path prefixed with a `/`.

**Comment by solleer** [comment]
> So perhaps we just need a $documentRoot variable which defaults to getcwd() but can be overridden with a custom path which is then used for any path prefixed with a /
I like this idea

**Comment by TomBZombie** [comment]
The only issue i see is that it might be a little confusing. Generally `/` means absolute path on the server. Maybe we could take the idea of the home directory `~/` to mean document root? Assuming no script would want to really use that path? Reagrdless, I think this is the best idea. I generally prefer loading files relative to one another so I can have file.tss reference `partial.tpl` from the same directory but can see why this is useful in some situations.

I'm not sure which is the better `/` or `~/` or something else entirely but it's certainly a useful feature

**Comment by solleer** [comment]
I guess we can keep it as `/` until there is an issue

**Comment by TomBZombie** [comment]
I think `/` is the sensible approach, after all there's never going to be  (or rather, shouldn't be!) a web server where you'll have access to anything outside a directory or two up.
