### ISSUE TITLE
Use Symfony Css Selector

### ISSUE THREAD

**Issue by hason** [Level-2/Transphporm#132]
It is more robust: http://symfony.com/doc/current/components/css_selector.html

**Comment by TomBZombie** [comment]
It doesn't seem to support any selectors not currently supported by transphporm, regardless, it's not suitable here for several reasons:

1) Transphporm requires registration of custom pseudo properties so we can use  for example: `div:data[usertype=admin]`, the symfony library would not allow this. I don't know whether it's extendable (documentation is sparse) but even if it is, it won't be able to know about the data assigned to a specific element and other expressions such as setting attribute properties where we have custom pseudos `a.facebook:attr[href] {content: "facebook.com/mypage"; }`

2a) It will be create a needless overhead. Transphporm parses the entire TSS document into tokens once which are then used by both the CSSToXPath class and for parsing the rules/properties in the sheet itself. Using the symfony library would require parsing the sheet and then sending the CSS selectors off to the third party library for parsing again. 

2b) It requires dozens of classes to do what Transphporm does in 150 lines of code https://github.com/Level-2/Transphporm/blob/master/src/Parser/CssToXpath.php
