### ISSUE TITLE
Using Transphporm with php gettext

### ISSUE THREAD

**Issue by Avik-B** [Level-2/Transphporm#138]
I just started fiddling with Transphporm, and having the following issue:
Currently I use php gettext for translating my website. Here is how my temlapte would look like:

Home.template.php:
```
<!DOCTYPE html>
<html>
<head>
                <title></title>
</head>
<body>
                <nav>
                </nav>
                
                <main>
                                <h1><?php echo __(“Home page header”); ?></h1>
                                <p><?php echo __(“Home page description”); ?></p>
                </main>

                <footer>
                </footer>
</body>
</html>
```
Now this would’ve worked perfectly if it was parsed as php. But with Transphporm php does not parse it. 
Now the only way to work with Transphporm with gettext is if I pass array pf data like so:
```
$data = [
                “lang”=> [
                                “home_title” => __(“Home page header”),
                                “home_desc” => __(“Home page description”),
                ],
];

$page_tpl = new Builder($layout_xml, $home_tss);
$out = $page_tpl->output($data)->body;
echo $out;
```
and then in the home.tss file:
```
main h1 {content: data(lang.home_title)}
main p   {content: data(lang.home_desc)}
```
now this works fine. But the issue is, lets say if home page template has 100 of those line. I have to declare 100 more of these as arrays and pass them. This is not really efficient. while reusability maybe increased but the home/landing page is 99% static and 1% dynamic content.
The home page was not meant to be reusable. Decalring 100s of static line as a variable would be a huge pain.
So my question is what would be the best approach when dealing with this situation.

Is there anyway to allow php gettext function to be executed on the template file first then parse them with Transphporm?
Thanks.

**Comment by TomBZombie** [comment]
You're better off creating a custom module for this. Transphporm is extensible but the documentation needs improvement.

```
class GetTextModule implements \Transphporm\Module {
	
	public function load(Config $config) {
		$config->getFunctionSet()->addFunction('gettext', new GetTextFunction());
	}
}


class GetTextFunction implements \Transphporm\TssFunction {
	public function run(array $args, \DomElement $element) {
		return __($args[0]);
	}
}
```

Then:

```
$page_tpl = new Builder($layout_xml, $home_tss);
$page_tpl->loadModule(new GetTextModule());
```

This creates a module, the module can then change/extend the configuration of the instance. In this case, it extends transphporm with a new function:

```
$config->getFunctionSet()->addFunction('gettext', new GetTextFunction());
```

Which creates a function called `gettext` in transphporm. Then when transphporm comes across:

```
main p   {content: gettext("Home page description");}
```

It will call the `run` function in the associated class, `GetTextFunction` with an array of args, `$args[0]` being `"Home page description"`

You should be able to  even call the function `__` if you prefer (I haven't tested this, but I can't think of a reason __ wouldn't work):

```
		$config->getFunctionSet()->addFunction('gettext', new GetTextFunction());
```
Then use 

```
main p   {content: __("Home page description");}
```

## but let's make this even smarter

When `GetTextFunction::run()` is called, it gives you a reference to the matched element. In the example above, the `main p` element.

We could read the text out of the HTML directly:

```
class GetTextFunction implements \Transphporm\TssFunction {
	public function run(array $args, \DomElement $element) {
                $text = $element->firstChild->nodeValue;
		return __($text);
	}
}
```

Now, given the HTML:

````
<main>
  <p>Home page description</p>
</main>
```

The following TSS can be applied:

```
main p {content: gettext();}
```

And it will read `Home page description` from the node itself.

Taking this a step further still, we could use an attribute to:

````
<main>
  <p data-gettext="true">Home page description</p>
</main>
```

and apply the TSS

```
p[data-gettext] {content: gettext();}
````

And any paragraph, `<p data-gettext="true">$para_contents</p>`, with the attribute will have its contents replaced with a call to `__($para_contents)`

I don't think there is currently an easy way to have a wildcard, but this is certainly a good reason to create one.

When I have more time I'll try to implement `*` wildcards so then it would be possible to do:

```
*[data-gettext] {content: gettext();}
```

*this may work currently: `[data-gettext] {content: gettext();}` but I'm not sure*

**Comment by solleer** [comment]
@TomBZombie `[data-gettext] {content: gettext();}` does currently work

**Comment by TomBZombie** [comment]
Excellent, then yes then the solution here is a single line of TSS:

```
[data-gettext] {content: gettext();}
```

And then add the attribute to any element you like e.g. `<h1 data-gettext="true">Heading text</h1>`  and it will do the equivalent of 

```
<h1 data-gettext="true"><?= __('Heading text'); ?></h1>
```

To tidy it up, after the first rule you could possibly even do:

```
[data-gettext]:attr(data-gettext) {display: none}
```

To remove the `data-gettext` attribute from the final HTML that gets rendered.

**Comment by Avik-B** [comment]
WOW it works! 👍 
Thanks a lot. I actually found another way to did it:

i created a custom data object and pass it to Transphporm. 
```
class data {
    public function __($string){
        return __($string);
    }
}
```
```
        $data = new data;
        $page_tpl = new Builder($layout_xml, $home_tss);
        $out = $page_tpl->output($data)->body;
        echo ($out);
```
now inside the `home.tss` file i could use:
```
title, h1[lang="hero-text-top"] {
    content: data(__("i can be translated!"));
}
```

it worked. But extending with custom module is better though. ;)
i could not find any info on how to create extension module though. 😕 Hope we could get a wiki about this, that would be awesome.
