### ISSUE TITLE
HTML formatting is broken

### ISSUE THREAD

**Issue by Avik-B** [Level-2/Transphporm#139]
Found this bug while testing with HTML elements.

the following does not work:
```
    content: "Change <i>the </i>appearance";
    format: html;
```

but this works:
```
    content: "<i>Change the appearance</i>";
    format: html;
```

also it does not work either if the string does not have any html elements in it. Also single tags like `<br>` does not work.

**Comment by TomBZombie** [comment]
Yes, unfortunately html formatting requires XML, wrap the content in a container element and use `<br/>` and it should work. 

I'll try to update it to support HTML

**Comment by solleer** [comment]
It uses the same thing as the template function. The problem is that the domdoc has an issue when there is no root

**Comment by Avik-B** [comment]
i did some test and it seems when i declare the format, the custom attribute selectors does not work.

the following works:
```
<h4 id="id1">dfgvdfxgv</h4>
<h4 id="id2" >dfgvdfxgv</h4>
```
```
#id1 {
    content: "<div>id1!!<br/>test</div>";
    format: html;
}

#id2 {
    content: "<div>id2!!<br/>test</div>";
    format: html;
}
```

but when i try to use attribute selector it does not work. Also it creates a loop that pretty much nearly crashes the browser. Also windows Explorer.exe pcpu usage jumps to 40%, so does the apache.

```
h4[gettext-html] {
    content: "<div>heya!!<br/>this will definitely crash</div>";
    format: html;
}
```

and this one cause crash too:
```
[gettext-html] {
    content: "<div>heya!!<br/>this will also crash</div>";
    format: html;
}
```

**Comment by solleer** [comment]
This test passes
```php
public function testHTMLFormat2() {
        $xml = '
<h4 id="id1">dfgvdfxgv</h4>
<h4 id="id2" >dfgvdfxgv</h4>';

        $tss = ';
h4[gettext-html] {
    content: "<div>heya!!<br/>this will definitely crash</div>";
    format: html;
}';
```

**Comment by Avik-B** [comment]
try the test with custom attribute and it will crash.
```
$xml = '
<h4 gettext-html="true">dfgvdfxgv</h4>
<h4 gettext-html="true">dfgvdfxgv</h4>
<h4 gettext-html="true">dfgvdfxgv</h4>
';

$tss = ';
h4[gettext-html] {
    content: "<div>heya!!<br/>this will definitely crash</div>";
    format: html;
}';

```
make sure `h4` has `gettext-html` custom attribute.
it should be parsed to something like:

```
<h4 gettext-html="true"><div>heya!!<br/>this will definitely crash</div></h4>
<h4 gettext-html="true"><div>heya!!<br/>this will definitely crash</div></h4>
<h4 gettext-html="true"><div>heya!!<br/>this will definitely crash</div></h4>
```
but it does not. It pretty much crashes apache and my system with it. :S

**Comment by solleer** [comment]
This passes
```php
public function testHTMLFormat2() {
        $xml = '
<h4 gettext-html="true">dfgvdfxgv</h4>
<h4 gettext-html="true">dfgvdfxgv</h4>
<h4 gettext-html="true">dfgvdfxgv</h4>
        ';

        $tss = ';
h4[gettext-html] {
            content: "<div>heya!!<br/>this will definitely crash</div>";
            format: html;
        }';

$template = new \Transphporm\Builder($xml, $tss);

$this->assertEquals($this->stripTabs('<h4 gettext-html="true"><div>heya!!<br />this will definitely crash</div></h4>
<h4 gettext-html="true"><div>heya!!<br />this will definitely crash</div></h4>
<h4 gettext-html="true"><div>heya!!<br />this will definitely crash</div></h4>'), $this->stripTabs($template->output()->body));
    }
}
```

**Comment by Avik-B** [comment]
this is strange. Throws error for me and crashes. I will do some checks to see if it is on my end or something.

**Comment by Avik-B** [comment]
@solleer okay i did some test and found out why it was only happening to me.
It seems you are running the latest code from github.
For me i was using composer which is still on v 1.1.1. and the bug i mentioned is present on that version.

I tried with a direct copy from github's master branch and the issue is fixed. Maybe you should tag it as a release for those who are using composer.

**Comment by Avik-B** [comment]
i am closing this issue as it is fixed in the latest update from github.
