### ISSUE TITLE
using 2 iterations: Bug or Feature ?

### ISSUE THREAD

**Issue by tontof** [Level-2/Transphporm#14]
I don't know it's a bug or a feature, but I can not use 2 iteration inside one rule.
```
#user {content: iteration(firstname), " ", iteration(lastname);}
```
That's not very problematic, I was just wondering if it's a wanted behavior ? (maybe because of technical reasons)

**Comment by TomBZombie** [comment]
I've never needed this myself but it certainly should work. If there's a technical reason for it not to it needs to be worked around as this behaviour is certainly not desirable. Let me take a look, it should be fairly trivial to fix.

**Comment by TomBZombie** [comment]
I've updated the parser to solve this bug.

**Comment by tontof** [comment]
Thanks ! It works great !
