### ISSUE TITLE
html format breaks utf-8 encoding when "&" character is present in string

### ISSUE THREAD

**Issue by Avik-B** [Level-2/Transphporm#140]
I was trying out Russian language and found this bug.
here is how to reproduce it.

```php
$data = [
    "text" => "<p>this is half english and половина России &</p>",
];
```

```css
h1 {
	content: data(text);
	format: html;
}
```

now the expected output is:
```
<h1><p>this is half english and половина России &</p></h1>
```

but here is the result i got:
```
<h1><p>this is half english and Ð¿Ð¾Ð»Ð¾Ð²Ð¸Ð½Ð° Ð Ð¾ÑÑÐ¸Ð¸ &</p></h1>
```

the problem only occurs if there is a `&` character present. If you remove it it works perfectly fine.

**Comment by Avik-B** [comment]
i am using the latest code from github this time, and the problem persists.

**Comment by TomBZombie** [comment]
If you use `    "text" => "<p>this is half english and половина России &nbsp;</p>",` is the problem resolved? The code you have isn't valid HTML or XML so will cause issues.

**Comment by TomBZombie** [comment]
I'm struggling to even get a bare bones test to run. Even this:

```
$doc = new \DomDocument('1.0', 'UTF-8');

$doc->loadHTML('<p>this is half english and половина России</p>');

$output = '';
foreach ($doc->documentElement->childNodes as $node) $output .= $doc->saveXML($node, LIBXML_NOEMPTYTAG);

echo $output;
```

Seems to print out invalid characters, which is what transphporm does behind the scenes.

**Comment by Avik-B** [comment]
the following also don't work.
```
$template = '<img src="http://test.com/img.jpg">';
```

but if you add `/` after the image tag it works.
```
$template = '<img src="http://test.com/img.jpg" />';
```
seems like invalid xml issue.


> Making the HTML valid by using &amp; fixes it.

unfortunately i was trying to use `&nbsp;`, not just `&`. This won't work in that case.

**Comment by TomBZombie** [comment]
That's strange, transphorm uses `DomDocument`s loadhtml() function which should support HTML tags. I'll have to do some specific tests. Likely it means changing the way DomDocument processes the HTML code.

**Comment by Avik-B** [comment]
ok i found the fix for this issue:
In the `Template.php` file `line 35` has the load function:

```
	/** Loads a HTML or XML document */
	private function loadDocument($doc) {
		libxml_use_internal_errors(true);
		if ($this->document->loadXml($doc) === false) {
				$this->document->loadHtml($doc);

				if (strpos($doc, '<!') !== 0) {
					$templateNode = $this->document->getElementsByTagName('template')[0];
					$this->document->replaceChild($templateNode, $this->document->documentElement);
				}
		}
		libxml_clear_errors();
	}
```
according to this Stackoverflow post the issue occurs because it parses the string as `ISO-8859-1`, which messes up the encoding.

Here is the modified function for `loadDocement`

```
	/** Loads a HTML or XML document */
	private function loadDocument($doc) {
		libxml_use_internal_errors(true);
		if ($this->document->loadXml($doc) === false) {
				$this->document->loadHtml(mb_convert_encoding($doc, 'HTML-ENTITIES', 'UTF-8'));

				if (strpos($doc, '<!') !== 0) {
					$templateNode = $this->document->getElementsByTagName('template')[0];
					$this->document->replaceChild($templateNode, $this->document->documentElement);
				}
		}
		libxml_clear_errors();
	}
```

This solves the issue on my end.

**Comment by TomBZombie** [comment]
Nice fine, unfortunately not all PHP servers have the mbstring extension enabled/installed. Also from Stackoverflow this fix is  suggested: 

```
$this->document->loadHtml('<' . '?xml encoding="UTF-8">' . $doc);
```

Which would be a better solution in this case. That doesn't solve the issue of `<img>` not working though.

**Comment by Avik-B** [comment]
`<img>` tag issue is probably because php's `DomDoc` does not support hmtl5 tags. Maybe a thirdparty parsing library would solve this.

> Also from Stackoverflow this fix is suggested:
>>$this->document->loadHtml('<' . '?xml encoding="UTF-8">' . $doc);

This also works. Maybe you could push an update to github after it passes the tests. 
This issue made me crazy, wasted hours trying to narrow this down.

**Comment by Avik-B** [comment]
added a pill request to fix this. We need unit testing though.
#141

**Comment by Avik-B** [comment]
closing this issue as it has been fixed and merged.

**Comment by solleer** [comment]
This test doesn't pass
```php
public function testUTF8() {
    $xml = "<p>this is half english and половина России &</p>";
    $template = new Builder($xml);

	$this->assertEquals('<p>this is half english and половина России &</p>', $template->output()->body);
}
```

**Comment by TomBZombie** [comment]
It's the test that's wrong there. The output is correct, & is replaced with the entity `&amp;` `<p>this is half english and половина России &amp;</p>'`
