### ISSUE TITLE
HTML formatter

### ISSUE THREAD

**Issue by hor-net** [Level-2/Transphporm#142]
Maybe i got it wrong, but i used the HTML formatter as a sort of "raw" output.

I discovered that if the content passed to the formatter doesn't start with a < Transphporm tries to load the whole string as if it was an external template.

There is a simple fix, just wrap everything with <div> </div> in HTMLFormatter::html if the first character of $val is not < 

I can make a pull request if you want

Saverio

**Comment by solleer** [comment]
The reason it does that is because internally it uses the template function.

**Comment by hor-net** [comment]
Yes i know i've inspected the code.
the problem is in Builder::loadTemplate 

```
        //Load a template, firstly check if it's a file or a valid string
	private function loadTemplate() {
		if (trim($this->template)[0] !== '<') {
			$xml = $this->cache->load($this->template, filemtime($this->template));
			return $xml ? $xml : ['body' => file_get_contents($this->template), 'headers' => []];
		}
		else return ['body' => $this->template, 'headers' => []];
	}
```
there is a check for the first character being < if this is true is assumed as markup, otherwise the template is loaded.

This is not a good check IMHO because i'm trying to output the content of a "post" that may contain html formatting but it may NOT start with an html tag.

The wrapping solution i suggested above fixes the issue, but there should be a more elegant way to check if loadTemplate is given a file name or a markup code. (probably just checking for the existence of the file should be enough)

Saverio

**Comment by TomBZombie** [comment]
I don't think wrapping is the answer as it will cause an extra element to appear in the HTML. May not be an issue but might cause odd display issues if people have styled the element we choose to use.

A better way might be to look for "\n":

```
		if (trim($this->template)[0] !== '<' || strpos($this->template, "\n")  !== false) {
```

We could use `is_file` but that will add a performance overhead. Everywhere a template is loaded it will perform a disk read which is significantly slower.

**Comment by TomBZombie** [comment]
Actually we should be able to use `<template>` which is automatically stripped on output.

**Comment by hor-net** [comment]
so you mean wrapping the data inside a <template> tag? since it's stripped out it could be a solution. A new line doesn't guarantee here anything since the string that may contain html could not contain a newline...
