### ISSUE TITLE
Javascript in template file is not working properly

### ISSUE THREAD

**Issue by Avik-B** [Level-2/Transphporm#144]
Basically i have this simple javascript on my template file:
```js
<script type="text/javascript">
    $(document).ready(function () {
        hljs.initHighlightingOnLoad();
    });
</script>
```

and what i get is this:
![opera_2017-03-13_09-00-03](https://cloud.githubusercontent.com/assets/2894306/23840532/04582e36-07cc-11e7-9264-e8f002e4cf6d.png)

the browser throws error. Is there anyway to include Javascript in the template file?

**Comment by TomBZombie** [comment]
Can you give an example that creates this? The following:

```php
		$template = '<html><head>

		<script>
		$().ready(function() {});
		</script>
		</head>
		<body></body></html>';

		$template = new \Transphporm\Builder($template, '');

		var_dump($template->output());

```

Prints:

```html
<html><head>                                                                                                                                  
                                                                                                                                                            
                <script>                                                                                                                                    
                $().ready(function() {});                                                                                                                   
                </script>                                                                                                                                   
                </head>                                                                                                                                     
                <body></body></html>
```

**Comment by TomBZombie** [comment]
ok I've found the problem, it seems to be that `DomDocument::loadHTML` adds the CDATA, unfortunately it also seems to ignore the option LIBXML_NOCDATA.

```php
$template = '<!doctype html><html><head>

		<script>
		$().ready(function() {});
		</script>
		</head>
		<body>

Here\'s a br to create invalid XML to trigger loadHTML<br>
</body></html>';

		$template = new \Transphporm\Builder($template, '');

		var_dump($template->output());
```

outputs:

```php
$template = '<!doctype html><html><head>

		<script>
		$().ready(function() {});
		</script>
		</head>
		<body>

Here\'s a br to create invalid XML to trigger loadHTML<br>
</body></html>';

		$template = new \Transphporm\Builder($template, '');

		var_dump($template->output());
```

Unfortunately, both saveXML() and loadHTML() seem to ignore the  LIBXML_NOCDATA option. We might have to do an ugly hack and do str_replace on the final string,

**Comment by TomBZombie** [comment]
Upon further investigation it looks like we can use `saveHtml` and `loadHtml` throughout to solve this, but it causes some potential issues:

1)  It outputs HTML (e.g. `<img src="foo.jpg">` instead of `<img src="foo.jpg" />`. Probably not an issue in 99% of cases but if anyone is using Transphporm for XML documents then it will break what they're doing.

2) all relevant tests will need changing to omit the trailing slash.

The first issue is the main one we'll run into.  Perhaps we just need a way to configure transphorm in XML or HTML mode. Perhaps it should even just look for `<!DOCTYPE HTML>` vs `<?xml` to make that call.

**Comment by TomBZombie** [comment]
Ok I've fixed this in a really simple way that won't break BC or anyone using transphporm for XML.

- As before it tries to load the document as XML
- As before, if it fails it loads the document as HTML
- However, now, when it saves, if the document was loaded as XML it uses `saveXML()`, if the document was loaded as HTML it calls `saveHTML()`

**Comment by Avik-B** [comment]
commit #144 throws error.
`Parse error: syntax error, unexpected '(' on Template.php line 77`

I am using php 5.6 btw.

**Comment by TomBZombie** [comment]
Ah, it looks like PHP5.6 doesn't support `($this->closure)();` I'll update the code.

**Comment by TomBZombie** [comment]
Try the latest commit, it's using the rather ugly `call_user_func` but should work as intended.

**Comment by Avik-B** [comment]
thanks. it worked. 😄
