### ISSUE TITLE
Include XML as filename and TSS as string

### ISSUE THREAD

**Issue by Mr-Chimp** [Level-2/Transphporm#15]
Hi, I think I potentially found a bug where I try to use Transphporm by loading the XML from a file and the TSS as a string. I get the following message: 
`Warning: file_get_contents(h1 {content: &quot;Replaced Title&quot;; }): failed to open stream: No such file or directory `

It is basically trying to use the TSS code as filename, I only have some simple TSS at the moment. Whilst writing this I realised this may be by design but it would be useful to be able to use one parameter via file and the other by string.

**Comment by TomBZombie** [comment]
Thanks, yes. Currently this is how it works: Either it loads them from files or it loads them from strings. I'm not sure there's an easy way to detect whether or not a tss string is a file or not and I was trying to avoid using file_exists() as file I/O is needlessly slow if it's nor required.

As a temporary workaround you could use the following:

```php
new \Transphporm\Builder(file_get_contents('file.xml'), 'h1 {content: "..."; }');
```

**Comment by Mr-Chimp** [comment]
Thanks for that, the workaround worked like a charm
