### ISSUE TITLE
FilePath

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#150]
I think this needs changing as it causes a few issues for managing paths. I had suggested using `:/` to represent cwd() but I think it should be modelled on PHP's include_path:

- Have a list of directories from where files can be loaded from
- Look in each directory for a file with the matching name with the first in the list taking precedence

**Comment by TomBZombie** [comment]
@solleer  I've moved this into its own branch: https://github.com/Level-2/Transphporm/tree/FilePath-IncludeDir let me know what you think, FilePath now looks like this:

```php

<?php
namespace Transphporm;
class FilePath {
	private $paths = ['.'];

	public function addPath($path) {
		$this->paths[] = rtrim($path, DIRECTORY_SEPARATOR);
	}

	public function getFilePath($filePath) {
		if (is_file($filePath)) return $filePath;
		else {
			foreach ($this->paths as $path) {
				if (is_file($path . DIRECTORY_SEPARATOR . $filePath)) return $path . DIRECTORY_SEPARATOR . $filePath;

			}
		}

		throw new \Exception($filePath . ' not found in include path: ' . implode(';', $this->paths));
	}
}

```

Rather than having multiple dirs being tracked and change, `addPath` basically works like set_include_path in php and allows adding directories where files can be loaded from. That way it will first look for `import.tss` in the current working directory, then each of the directories.

There could potentially be an issue here though, because each TSS file that's loaded has its path added to the include path, if there are multiple files with the same name in different directories it may cause an issue. This likely could be fixed by resetting the include path on @import, but that may introduce other problems. 

Overall though, I think this is a simpler solution:
```
$builder->addPath('path1');
$builder->addPath('path2');
```

When `@import` is used, it looks in both locations and the location of the current import file.

**Comment by solleer** [comment]
I like the idea but the same file names in different directories sounds like a big issue. What if it still had a base dir but that is only set by property hook and kept the ability to custom set additional paths

**Comment by TomBZombie** [comment]
I think you're right. I think we need some way of setting a precedence order per load so that when an `@import` is run it passes two things to getFilePath: The file to be imported and the location of the TSS file, this location would then take precedence : 

````php
	public function getFilePath($filePath, $baseDir = '') {
		if (is_file($filePath)) return $filePath;
		else if (is_file($baseDir . DIRECTORY_SEPARATOR . $filePath)) return $baseDir . DIRECTORY_SEPARATOR . $filePath;
		else {
			foreach ($this->paths as $path) {
				if (is_file($path . DIRECTORY_SEPARATOR . $filePath)) return $path . DIRECTORY_SEPARATOR . $filePath;

			}
		}

		throw new \Exception($filePath . ' not found in include path: ' . implode(';', $this->paths));
	}
}
```

That way, the added included paths are basically just fallbacks and we can specify the baseDir for any getFilePath() call

**Comment by solleer** [comment]
Would this work for `template` and `json`?

**Comment by TomBZombie** [comment]
We would need some way of getting the current tss file into the template() call but if we did that then it would work in the same way

**Comment by TomBZombie** [comment]
Actually i think your idea was simpler. Have the baseDir set to the location of the TSS file in builder ( It doesn't need to be in propertyhook) then the order of precedence will be:

is_file($path) -- for absolute paths
is_file($baseDir . $path) 
Then look in any other path that's been set

**Comment by solleer** [comment]
I think it should work as it did just without setting the rootPath and allowing several include paths to be set

**Comment by TomBZombie** [comment]
yes you're right, I've amended the code, it's basically as you had it before but $customPath is an array.

**Comment by solleer** [comment]
```php
<?php
namespace Transphporm;
class FilePath {
	private $paths = ['.'];
        private $baseDir = '';

	public function addPath($path) {
		$this->paths[] = rtrim($path, DIRECTORY_SEPARATOR);
	}

        public function setBaseDir($baseDir) {
                $this->baseDir = $baseDir;
        }

	public function getFilePath($filePath) {
		if (is_file($filePath)) return $filePath;
		else if (is_file($this->baseDir . DIRECTORY_SEPARATOR . $filePath)) return $this->baseDir . DIRECTORY_SEPARATOR . $filePath;
		else {
			foreach ($this->paths as $path) {
				if (is_file($path . DIRECTORY_SEPARATOR . $filePath)) return $path . DIRECTORY_SEPARATOR . $filePath;

			}
		}

		throw new \Exception($filePath . ' not found in include path: ' . implode(';', $this->paths));
	}
}
```

**Comment by solleer** [comment]
Can this be closed
