### ISSUE TITLE
Syntax error in Value.php

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#152]
Line 150 of src/Parser/Value.php has a syntax error.

```
$ php -l vendor/level-2/transphporm/src/Parser/Value.php

Parse error: syntax error, unexpected '?' in vendor/level-2/transphporm/src/Parser/Value.php on line 150
```

**Comment by solleer** [comment]
Are you using php7?

**Comment by cxj** [comment]
Could we get a stable snapshot tagged or something of more recent code than the last release?  I've been using the HEAD of master to get what I needed, and it was working until I just ran `composer update` tonight which grabbed the above syntax error.  Thanks!

**Comment by cxj** [comment]
PHP 5.6.27 at the moment.  Will be migrating to PHP 7 in the next month or two.

**Comment by cxj** [comment]
If you're going to require PHP 7, you should update the requirements in the `composer.json` file as well as in the documentation.

**Comment by cxj** [comment]
It would be ideal to have a branch or release prior to changes which require PHP 7.

**Comment by TomBZombie** [comment]
Yes, you're right. I'll refactor it so php7 isn't required, there's no real reason this can't be expressed without the more convenient shorthand notation.

**Comment by cxj** [comment]
Fantastic.  Thanks much!
