### ISSUE TITLE
Value 0 not displayed

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#153]
In commit a9d2643e683c181406bc7c2e096b722536baf7b1, if a token has a value of zero, it's not displayed at all even if I coerce it to string type, although the place holder is replaced with an empty string.

```php
<?php
require "vendor/autoload.php";

$xml = '<p>Exception code: <span class="code">unknown</span></p>';
$tss = '.code { content: data(errorCode); }';
$tpl = new Transphporm\Builder($xml, $tss);

$data['errorCode'] = 0;
echo $tpl->output($data)->body . PHP_EOL;

$data['errorCode'] = (string)0;
echo $tpl->output($data)->body . PHP_EOL;

$data['errorCode'] = (string)0 . 'foo';
echo $tpl->output($data)->body . PHP_EOL;
```

Output:
```html
<p>Exception code: <span class="code"></span></p>
<p>Exception code: <span class="code"></span></p>
<p>Exception code: <span class="code">0foo</span></p>
```

Expected output:
```html
<p>Exception code: <span class="code">0</span></p>
<p>Exception code: <span class="code">0</span></p>
<p>Exception code: <span class="code">0foo</span></p>
```

**Comment by cxj** [comment]
Have tested this again in commit 0370d26 (current head today 30-May), same behavior.  

If someone could point me at the right file, I'd attempt making a fix in a pull request.

**Comment by solleer** [comment]
I've looked into it a bit and can't quite find where the issue is. I'll keep looking.

**Comment by cxj** [comment]
Great, thanks!  Will download now and test.

**Comment by cxj** [comment]
My tests show it to be working correctly now.
