### ISSUE TITLE
<style scoped="scoped"> content turned to CDATA

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#154]
I'm not sure if this is a Transphporm behavior or a PHP problem.

I've got a "partial" template with something like this:
```html
<div class="list-claims-form">
    <style scoped="scoped">
        fieldset, legend { width:75%; }
    </style>
```

The generated HTML looks like this:
```html
<div class="list-claims-form">
<style  #scoped="scoped"><![CDATA[
        fieldset, legend { width:75%; }
    ]]></style>
```

As a result, my style appears to be ignored.

Is this because of the XML to HTML conversion?  Any advice?

**Comment by TomBZombie** [comment]
This should be fixed in git-master but I'll draft a new release shortly as there have been a lot of bugfixes since the last release.

**Comment by cxj** [comment]
Very much appreciated!  I love Transphporm.  :-)

**Comment by solleer** [comment]
Can this be closed?
