### ISSUE TITLE
Doctype present in XML but not in output

### ISSUE THREAD

**Issue by garrettw** [Level-2/Transphporm#158]
index.php:
```php
<?php
require 'vendor/autoload.php';
$template = new \Transphporm\Builder('layout.xml', 'home.tss');
echo $template->output()->body;
```

layout.xml:
```xml
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li><a href="/">Home</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</header>
		<main>

		</main>
		<footer>

		</footer>
	</body>
</html>
```

home.tss:
```css
title {content: "My Site"}
main {content: template("home.xml")}
footer span {content: "now"; format: date "Y"}
```

home.xml:
```xml
<?xml version="1.0"?>
<template>
	<p>Welcome to my website</p>
</template>
```
----
output (using php 5.6):
```html
<html>
        <head>
                <meta charset="utf-8">
                <title>My Site</title>
        </head>
        <body>
                <header>
                        <nav>
                                <ul>
                                        <li><a href="/">Home</a></li>
                                        <li><a href="about.html">About</a></li>
                                        <li><a href="contact.html">Contact</a></li>
                                </ul>
                        </nav>
                </header>
                <main>
        <p>Welcome to my website</p>
</main>
                <footer>

                </footer>
        </body>
</html>
```

As you can see, the doctype is missing from the output.

**Comment by solleer** [comment]
I can't seem to duplicate this issue

**Comment by garrettw** [comment]
I'll pull the latest code and try again to be sure.

**Comment by solleer** [comment]
Can you replicate it

**Comment by garrettw** [comment]
Sorry it took so long. Yes, after running `php composer.phar update` which installed ea3e1bfb5d790e0d9ff87283cd43cb09e1ccd4d3, the output is still the same as what I posted above.

**Comment by solleer** [comment]
For some reason this tage, `<meta charset="utf-8">`, is causing it to remove the doctype

**Comment by garrettw** [comment]
Oh! I don't know how I missed that. As this is XML, I needed a closing slash at the end of the tag – and that fixed it.

**Comment by garrettw** [comment]
But wouldn't that make the XML document not well-formed? Shouldn't I get a parsing error instead?

**Comment by solleer** [comment]
Since it isn't valid xml it uses the html loader. The issue lies with the html loader.

**Comment by solleer** [comment]
When it uses `loadHTML` it removes the doctype

**Comment by solleer** [comment]
@TomBZombie I need some help with this
I can't get this test to pass
```php
public function testDoctypeUsingLoadHTML() {
    $xml = '<!DOCTYPE html><html><head><title></title></head><body><img></body></html>';

    $tss = 'title {content: "My Site"}';

    $template = new \Transphporm\Builder($xml, $tss);

    $this->assertEquals($this->stripTabs('<!DOCTYPE html><html>
<head>
<title>My Site</title>
</head>
<body><img></body>
</html>'), $this->stripTabs($template->output()->body));
}
```

**Comment by TomBZombie** [comment]
This is certainly something to do with `loadHTML` or `saveHTML`. I'm trying to minimally re-create what transphporm is doing. This works as expected:


```php
<?php
$html = '<!doctype html><body>Hello</body>';


$doc = new \DomDocument();
$doc->loadHtml($html,  LIBXML_HTML_NODEFDTD | LIBXML_HTML_NOIMPLIED);

echo $doc->saveHtml();

```

Though `!doctype` becomes `!DOCTYPE`, which might be something we have to live with. I'll keep looking.

**Comment by TomBZombie** [comment]
This is some nice DomDocument WTFery:

```php
echo $doc->saveXml($doc->doctype);
```

Prints the doctype correctly.

```php
echo $doc->saveHtml($doc->doctype);
```

Does not. I've force the line that prints (or doesn't print) the doctype to run through `saveXml` and everything works.

**Comment by TomBZombie** [comment]
But it does always make the doctype uppercase. This is a minor problem we could work around, but I don't think it will cause any problems outside needing to use uppercase in all unit tests.

**Comment by garrettw** [comment]
[Maybe this has something to do with it.](http://php.net/manual/en/domdocument.loadhtml.php#86450)
Could `loadHTML()` be thinking the HTML5 doctype is invalid and thus removing it? Other comments on that page point out other issues with loading HTML5 documents, so it could be possible that `loadHTML()` just hasn't been updated properly.

I think uppercase DOCTYPE is proper and correct anyway.

**Comment by garrettw** [comment]
FYI I just ran my layout.xml file through Tom's minimal test code above, and the doctype was in the output as it should be.
