### ISSUE TITLE
Not sure if/how these Scrutinizer issues should be fixed

### ISSUE THREAD

**Issue by garrettw** [Level-2/Transphporm#160]
I found the following issues in Scrutinizer which looked like they could/should be fixed, but I didn't make the changes myself because they'd need to be done by someone more familiar with the code base.
The changes I could handle myself are in #159.

[`Formatter\Nl2br::nl2br()` resembles PHP4-style constructor](https://scrutinizer-ci.com/g/Level-2/Transphporm/issues/master/files/src/Formatter/Nl2br.php?orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-26022190) -- either the class or function name should probably change

[`Parser\Last::process()` is duplicated in `Parser\Value::processLast()`](https://scrutinizer-ci.com/g/Level-2/Transphporm/issues/master/files/src/Parser/Last.php?orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-69088795) -- should be factored out somehow
[`Parser\Last::processLastUnexpected()` is almost duplicated in `Parser\Value::processLastUnexpected()`](https://scrutinizer-ci.com/g/Level-2/Transphporm/issues/master/files/src/Parser/Last.php?orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-69088796) -- can these be made similar enough to factor out, or not?

[`Parser\Sheet::stripComments()` is duplicated in `TSSValidator::stripComments()`](https://scrutinizer-ci.com/g/Level-2/Transphporm/issues/master/files/src/Parser/Sheet.php?orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-74938739) -- it's basically static so probably should be factored out somehow
    
[`TSSFunction\Template::$baseDir` is unused](https://scrutinizer-ci.com/g/Level-2/Transphporm/issues/master/files/src/TSSFunction/Template.php?orderField=path&order=asc&honorSelectedPaths=0#inspectioncomment-49431906) -- was it supposed to be called $filePath?

**Comment by solleer** [comment]
I have now fixed all but the `stripComments` issue
