### ISSUE TITLE
:before results in reverse order?

### ISSUE THREAD

**Issue by rdeelstra** [Level-2/Transphporm#165]
Hi Tom,

Really like this framework, great work.

The :before pseudo-element results in a reverse order when there are more than one elements
`body:before {content:template("ui/xml/default/default.xml");}`

Where default.xml is
```
<header role="banner"></header>
<nav id="nav-primary" role="navigation"></nav>
<main role="main"></main>
<footer></footer>
```

Maybe there is a better way through the Generator class or somewhere before this is generated to reverse the results, but I fixed it like this in Transphporm\Property\ContentPseudo\BeforeAfter:
```
    public function run($value, $pseudoArgs, $element) {
        if ($this->insertLocation === "before") {
            $result = [];
            foreach($this->content->getNode($value, $element->ownerDocument) as $node) {
                $result[] = $node;
            } 
            foreach (\array_reverse($result) as $node)
                $element->insertBefore($node, $element->firstChild);
        } else if($this->insertLocation === "after")
            foreach ($this->content->getNode($value, $element->ownerDocument) as $node)
                $element->appendChild($node);
    }
```

Btw:
```
foreach ($this->content->getNode($value, $element->ownerDocument) as $node) {
    if ($this->insertLocation === "before") $element->insertBefore($node, $element->firstChild);
    else if ($this->insertLocation === "after") $element->appendChild($node);
}
```

This would be better performance-wise because the $this->insertLocation is already known, don't have to be in a loop I guess:
```
        if ($this->insertLocation === "before")
            foreach ($this->content->getNode($value, $element->ownerDocument) as $node)
                $element->insertBefore($node, $element->firstChild);
        else if ($this->insertLocation === "after")
            foreach ($this->content->getNode($value, $element->ownerDocument) as $node)
                $element->appendChild($node);
```

Best regards, Rinnert

**Comment by TomBZombie** [comment]
The underlying cause of this issue is that `default.xml` is not valid XML. All XML files require an enclosing tag.

This `default.xml` will work:

```xml
<div>
<header role="banner"></header>
<nav id="nav-primary" role="navigation"></nav>
<main role="main"></main>
<footer></footer>
</div>
```

But obviously include the `<div>` transphporm also optionally looks for an enclosing `<template>` element:

```xml
<?xml version="1.0"?>
<template>
<header role="banner"></header>
<nav id="nav-primary" role="navigation"></nav>
<main role="main"></main>
<footer></footer>
</template>
```

which will achieve what you want. However, it would be better if, as you suggest, Transphporm did correctly support non-well-formed partials.

**Comment by garrettw** [comment]
I didn't realize that it looks for an enclosing `<template>` tag -- good to know.

**Comment by TomBZombie** [comment]
The reason this happens is that each time it calls `insertBefore` it reads the current first child of the element:

```php
			if ($this->insertLocation === "before") $element->insertBefore($node, $element->firstChild);
```

Each time it iterates, `$element->firstChild` is the element that was just inserted: It inserts the `header`, moves on to the `nav` and inserts it before the header that's now the first child of the element.

I've fixed this by storing the original first child element of the node being inserted into:

```php

		$currentFirst = $element->firstChild;

		foreach ($this->content->getNode($value, $element->ownerDocument) as $node) {
			if ($this->insertLocation === "before") $element->insertBefore($node, $currentFirst);
			else if ($this->insertLocation === "after") $element->appendChild($node);
		}
```

You're right on the performance, we already know the insert location, I'll change it to handle that better too.

**Comment by TomBZombie** [comment]
The latest commit fixes this issue and adds a test for it. I also managed to remove the if statement entirely.

**Comment by garrettw** [comment]
Nicely done 😎
