### ISSUE TITLE
:after not working for attributes

### ISSUE THREAD

**Issue by bjoern-tantau** [Level-2/Transphporm#167]
I would like to append to the class attribute, but the previous content is overwritten.

```
$data = new stdclass;
$xml = '<h1 class="foo">Example Title</h1>';
$tss = 'h1:attr(class):after {content: " AFTER";}';
$template = new \Transphporm\Builder($xml, $tss);
echo $template->output($data)->body;
```

Expected output:
`<h1 class="foo AFTER">Example Title</h1>`

Given output:
`<h1 class=" AFTER">Example Title</h1>`

Alternatively it could be useful to be able to reference the current content of a selected element itself. Maybe with
`h1:attr(class) {content: content(), " AFTER";}`

**Comment by TomBZombie** [comment]
Yes, you can do this but with a slightly different syntax. You can read the current value for the class attribute and concatenate it:

```
h1:attr(class) {content: attr(class), " AFTER"; }
```

But yes, perhaps this would be a useful addition

**Comment by bjoern-tantau** [comment]
Strange, `attr(class)` isn't working in my particular case, but it does work in the test case. I'll investigate further.

**Comment by bjoern-tantau** [comment]
It doesn't work if `$data` is passed in as an array.

```
$data = ['class' => ' AFTER'];
$xml = '<h1 class="foo">Example Title</h1>';
$tss = 'h1:attr(class) {content: attr(class), data(class); }';
$template = new \Transphporm\Builder($xml, $tss);
echo $template->output($data)->body;
```

**Comment by solleer** [comment]
These tests pass fine for me:
```php
public function testConcatDataAndAttr() {
    $data = ['class' => ' AFTER'];
    $xml = '<h1 class="foo">Example Title</h1>';
    $tss = 'h1:attr(class) {content: attr(class) + data(class); }';
    $template = new \Transphporm\Builder($xml, $tss);

    $this->assertEquals($this->stripTabs('<h1 class="foo AFTER">Example Title</h1>'),
		$this->stripTabs($template->output($data)->body));
}

public function testConcatDataAndAttr2() {
    $data = ['class' => ' AFTER'];
    $xml = '<h1 class="foo">Example Title</h1>';
    $tss = 'h1:attr(class) {content: attr(class), data(class); }';
    $template = new \Transphporm\Builder($xml, $tss);

    $this->assertEquals($this->stripTabs('<h1 class="foo AFTER">Example Title</h1>'),
		$this->stripTabs($template->output($data)->body));
}
```

**Comment by TomBZombie** [comment]
This was fixed in the master branch, the current release supports the workaround using concatenation and the master branch and next release will support the syntax you described in the first post:

```css
h1:attr(class):after {content: data(class); }
```
