### ISSUE TITLE
:attr(href) throws error, stacktrace

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#168]
In commit ea3e1bfb5d790e0d9ff87283cd43cb09e1ccd4d3 (old) and also in commit a2274078ef64268a219165fe91e4ff106efb7a0f (latest as of August 28), this code:
```php
<?php
require "vendor/autoload.php";

$xml = '<a href="#" id="foo">My Link</a>';

$tss = <<<EOT
#foo:attr(href) {
    content: data(site.clientUrl),
    "https://example.com/find-members-form";
}
EOT;

$tpl = new Transphporm\Builder($xml, $tss);

$data['site']['clientUrl'] = "http://localhost.com/";

echo $tpl->output($data)->body . PHP_EOL;
```
Throws this error:

> Notice:
> Undefined index: COLON in /Users/chris/project/vendor/level-2/transphporm/src/Parser/Value.php on line 67

And gives me a stack backtrace.

The problem is the embedded COLON in the content literal string, i.e. the `https:`.  Since it's a literal string, Transphporm should not care what characters are in it.

**Comment by TomBZombie** [comment]
Hmm, I'm struggling to replicate this

```php
	public function testStringWithColon() {
		$xml = '<a href="#" id="foo">My Link</a>';

		$tss = '#foo:attr(href) {content: "http://foo/bar"; }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs('<a href="http://foo/bar" id="foo">My Link</a>'), 
			$this->stripTabs($template->output()->body));
	}
```

Passes.


```php
	public function testStringWithColon() {
		$xml = '<a href="#" id="foo">My Link</a>';

        	$tss = '#foo:attr(href) {content: "foo", "http://foo/bar"; }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs('<a href="foohttp://foo/bar" id="foo">My Link</a>'), 
			$this->stripTabs($template->output()->body));
	}
```


Passes.

```php
	public function testStringWithColon() {
		$xml = '<a href="#" id="foo">My Link</a>';

		$data =  ['foo' => 'bar'];
		$tss = '#foo:attr(href) {content: data(foo), "http://foo/bar"; }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs('<a href="barhttp://foo/bar" id="foo">My Link</a>'), 
			$this->stripTabs($template->output($data)->body));
	}
```

Passes.

All tested with the latest master.

**Comment by TomBZombie** [comment]
I thought it might be the `:` in the data:

```php
	public function testStringWithColon() {
		$xml = '<a href="#" id="foo">My Link</a>';

		$data =  ['foo' => 'bar:baz'];
		$tss = '#foo:attr(href) {content: data(foo), "http://foo/bar"; }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs('<a href="bar:bazhttp://foo/bar" id="foo">My Link</a>'), 
			$this->stripTabs($template->output($data)->body));
	}

```

Also passes.

**Comment by TomBZombie** [comment]
Ok I've managed to get a test to fail:

```php
	public function testStringWithColon() {
		$xml = '<a href="#" id="foo">My Link</a>';

		$data = (object)  ['site' => ['clientUrl' => 'bar:baz']];
		$tss = '#foo:attr(href) {
			content: data(site.clientUrl), 
			"http://foo/bar";
		}';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs('<a href="bar:bazhttp://foo/bar" id="foo">My Link</a>'), 
			$this->stripTabs($template->output($data)->body));
	}

````

**Comment by TomBZombie** [comment]
Strange, it's the newline here:

```diff
diff --git a/tests/TransphpormTest.php b/tests/TransphpormTest.php
index 68dc8a0..11c3ce5 100644
--- a/tests/TransphpormTest.php
+++ b/tests/TransphpormTest.php
@@ -1580,8 +1580,7 @@ ul li span {
 		$tss = '#foo:attr(href) {
 			content: 
 			data(site.clientUrl),
-			"http://foo/bar";       
-			 }';
+			"http://foo/bar";   }';
 
 		$template = new \Transphporm\Builder($xml, $tss);
 

````

which triggers the problem

**Comment by cxj** [comment]
That is strange.  I was able to "fix" my problem by removing the `http://hostname/` bit from the string I was using (it was an error anyway, since the whole idea was to prepend the correct site's URL to the path).

Sorry for the misleading remark about the colon.  The error message mentioned COLON and removing the colon seemed to fix it.

**Comment by TomBZombie** [comment]
The problem is actually the `//`. It's being treated as a comment so the rest of the line is ignored. I've got a  semi working fix but it's causing an infinite loop somewhere I can't quite track down

**Comment by garrettw** [comment]
Was this fully fixed?

**Comment by solleer** [comment]
I believe so. The problem was that the `//` in the text was causing the line to be treated as a comment. Since the tokenizer now deals with comments and the tests pass, I think it is fixed.

**Comment by TomBZombie** [comment]
Yes, but the tokenizer is rather messy. I began refactoring it so that each method is a class and moved some of the properties from the `Tokens` class into `Tokenizer` but it's not quite that simple as different methods require different properties
