### ISSUE TITLE
Comments not taken in account

### ISSUE THREAD

**Issue by jerrywham** [Level-2/Transphporm#173]
If we wrote something like that in tss file :
```tss
    .loggedin input[name="uuid"]:attr(value) { content:data(uuid); }
   /* .loggedin input[name="step"]:attr(value) { content:data(step); }*/
    .loggedin input[type="submit"]:attr(value) { content:data(CONTINUE); }
```
the last line is not taken in account and attribute "value" of submit input is not changed.

**Comment by TomBZombie** [comment]
I've fixed this in the latest commit. I'm re-writing the parser as it's messy at the moment so it won't appear in a release until I've done that, however the latest commit will work.
