### ISSUE TITLE
Possible to use conditionals and different templates in loop?

### ISSUE THREAD

**Issue by portablepage** [Level-2/Transphporm#179]
First of all: thank you for this library! I've been experimenting a lot with the concept of 'templateless' templates, and kept concluding that javascript would be much better suited for this. Until I ran into Transphporm :-)

I've been reading through the wiki a lot, but I can't find an example of how to use conditionals in a loop, or a different template for each post. For example if you have a list of posts:

```php
$data = [
    'posts' => [
         [
            'title' => 'Title 1',
            'show_image' => true,
            'layout' => 'layout1.xml'
         ],
         [
             'title' => 'Title 2',
             'show_image' => false,
             'layout' => 'layout2.xml'
         ]
    ]
];
```
In this example the condition 'show_image' can be true or false per post, and each post can have a different template/partial ('layout' variable). Is such a setup possible, or am I approaching this from the wrong angle?

**Comment by jerrywham** [comment]
Use something like this :
```css
div {content: template(data.posts.layout);}
```

**Comment by jerrywham** [comment]
Use something like this :
```xml
<div>
    <article></article>
</div>
```
``` css
div {repeat:data(posts)}
article {content:iteration(layout);}
```

**Comment by jerrywham** [comment]
Be careful of the path of the layout.

**Comment by jerrywham** [comment]
This is not an issue...

**Comment by portablepage** [comment]
Thanks a lot Jerry, your template iteration example works like a charm! 

I guess ‘show_image’ is not the best real world example, I was just wondering how you could do if/else logic in a loop.

You’re right, this is not an issue with Transphorm, you may close it

**Comment by jerrywham** [comment]
Yeh but I can't :)

**Comment by portablepage** [comment]
Haha, closed it ;-)

**Comment by TomBZombie** [comment]
Take a look here: https://github.com/Level-2/Transphporm/wiki/Basic-Usage:-Conditional-Logic#conditions-inside-loops for an example of how do perform conditional logic inside a loop :)

**Comment by portablepage** [comment]
Thanks Tom!
