### ISSUE TITLE
Relative times doesn't work

### ISSUE THREAD

**Issue by jerrywham** [Level-2/Transphporm#180]
If I wrote :
```php
$xml = '
<div>
</div>
';

$tss = 'div {content:"60 years ago"; format: relative;}
';

$template = new \Transphporm\Builder($xml, $tss);

echo $template->output()->body;
```
it display 
```html
<div>60 years ago</div>
```
and not 
``` html
<div>15/12/1957</div>
```
Where am I wrong ?

**Comment by TomBZombie** [comment]
To use formatting (of any kind) you need to use the `format` property:

```php
div {
  content: "now";
  format: date relative;
}
```

`content` can be set to a string e.g. `content: "15/12/2017" but it must be parseable by the DateTime class so "60 years ago" likely won't work as a valid date.

**Comment by jerrywham** [comment]
Ok. Thank you.
So the wiki must be updated because it mention `format:relative;` alone.

**Comment by jerrywham** [comment]
"60 years ago" is valid and it works (see : http://php.net/manual/en/datetime.formats.relative.php, Day-based Notations).Try this :
```php
$xml = '
<div>
    <article></article>
</div>
';

$tss = 'div {content:"60 years ago"; format: date  "d/m/Y" relative;}
';

$template = new \Transphporm\Builder($xml, $tss);

echo $template->output()->body;
```
Output is `17/12/1957`

**Comment by TomBZombie** [comment]
The date formatter takes a single argument, the format. You are giving it two formats, d/m/Y then relative. It is taking the first argument only

**Comment by jerrywham** [comment]
Ok, you're right. I've corrected.
