### ISSUE TITLE
repeat API

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#181]
@solleer  I think you added this but I'm going to change the way `repeat: 1, 4, loop` works to be `repeat: 1 4 loop`.

In CSS comma separated values are different sets of values passed into the same property. For example:

```css
box-shadow: 5px 10px #888888, 20px 20px #ffffff
```

Sets two shadows. Each comma separated value in CSS is applied the same way. 

our content property:

```css
content: "foo", "bar";
```
Works the same way as `box-shadow`, `box-shadow` creates multiple shadows, `content` creates multiple pieces of content. Effectively in CSS the `box-shadow` function is called multiple times by separating the arguments with commas, each argument is separated with a space.

It makes more sense to express `repeat` ranges as `repeat: x y loop`.

**Comment by solleer** [comment]
It should work both ways right now. A space is the same as a comma in that case
