### ISSUE TITLE
Transphporm\Hook\ElementData->getData result

### ISSUE THREAD

**Issue by ashcs** [Level-2/Transphporm#188]
Hi all!
I am trying to make the translation function similar to read-write attributes:
```php
class Translator implements \Transphporm\TSSFunction
{
    private $lang = [];
    public function run(array $args, \DomElement $element) {
        return vsprintf($this->lang[$element->textContent], $args);
    }
}
```
Where $this->lang[$element->textContent] for example is " Currently %s users online"
Using rules:
```css
#element {content: __();} 
#element {content: __(data(user_count));} 
```

But when I do not pass arguments, the root data array is unexpected passed instead of an empty array.  Is that really necessary?  How can I be sure that I do get the arguments from the tss rules, but not the root data?

**Comment by TomBZombie** [comment]
Complete code:

```
<?php
require 'vendor/autoload.php';


class Translator implements \Transphporm\TSSFunction
{
    private $lang = [];
    public function run(array $args, \DomElement $element) {
        return vsprintf($this->lang[$element->textContent], $args);
    }
}

class Module implements \Transphporm\Module {
	public function load(\Transphporm\Config $config) {
		$functionSet = $config->getFunctionSet();
		$functionSet->addFunction('__', new Translator());
	}
}

$template = new \Transphporm\Builder('<div id="element"> </div>', '#element { content: __(); }');
$template->loadModule(new Module);

var_dump($template->output(['foo' => 'bar'])->body);

```

**Comment by TomBZombie** [comment]
I've fixed this in the latest commit.

This is a fairly crude fix but it's better than changing the behaviour of `Transphporm\Parser\Value` to return an empty array, the behaviour of it returning the tokens is required elsewhere.
