### ISSUE TITLE
[Question] Can the formatting of the databinding and functions be different?

### ISSUE THREAD

**Issue by smolinari** [Level-2/Transphporm#19]
Hey Tom,

Transphporm is looking pretty good!

One question about the formatting of data bindings. From the docs....
```
$xml = '<h1>Original Title</h1>';

$data = 'My Title!'

$tss = 'h1 {content: data(); }';


$template = new \Transphporm\Builder($xml, $tss)

echo $template->output($data)->body;
```
This is what databinding looks like with array elements.
```
$tss = '
    h1 {content: data(title);}
    p {content: data(description);}
';
```
How would I get the values out of deeper arrays?

I guess this leads me into a suggestion, which I think we had discussed earlier. Could it be possible to express databindings with dot notation?

 ```
$tss = 'h1 {content: data; }';
```
or
```
$tss = '
    h1 {content: data.title;}
    p {content: data.description;}
';
```

To me, this simply looks better and if there is the ability at some point to define custom functions (or is it possible now?), it is easier to keep variable bindings and functions apart. For deeper values in an array, you just have more dots.

```
$tss = '
    h1.blog {content: data.blog.title;}
    p.blog {content: data.blog.description;}
';
```

Furthermore, I still feel that the formating function could also be in the form of a function, just like attr() function in normal CSS.

So, instead of this.
``` 
$xml = '
<div> </div>
';

$tss = 'div {content: "2015-12-22"; format: date}';

$template = new \Transphporm\Builder($xml, $tss);

echo $template->output()->body;

```
We'd have something like this:
```
$tss = 'div {content: format("date", "2015-12-22")}';
```

Or, go with a more JS style. 

```
$tss = 'div {content: date.format("2015-12-22")}';
```

I like that even better. I guess what I am looking for is simplicity and uniformity.

Or, can you maybe explain your reasoning for doing the default date and other functions and data binding as you have? It could be the start of a small section in the docs explaining the design decisions as they are and making it more clear how the system is supposed to work. :smile:  

Scott

**Comment by TomBZombie** [comment]
> How would I get the values out of deeper arrays?

This is already possible using the dot notation:

```php
content: data(array.key.obj.key);
```

> Or, can you maybe explain your reasoning for doing the default date and other functions and data binding as you have?


In both cases it's consistency with CSS grammar. In CSS external resources (e.g. images) are referenced using `url(####)` The data() function works in TSS in exactly the same way. It says "Load an external resource, and here is its location"

For formatting, in CSS we don't have:

```php
p:before {content: "foo".format("uppercase")};
```

We have:

```php
p:before {content: "foo"; text-transform: uppercase; }
```

They're not really function calls, per-se, they're descriptions of how the element should be styled. The same is true in CSS. The `format` options is just a description of how the content is displayed, it's not really a function call.

This is currently undocumented but it is possible to add custom formatters. See `testCustomFormatter`

```php
	public function testCustomFormatter() {
		$template = '
			<div>Test</div>
		';
		$tss = 'div {content: "test"; format: reverse}';
		$template = new \Transphporm\Builder($template, $tss);	
		require_once 'tests/ReverseFormatter.php';
		$template->registerFormatter(new ReverseFormatter);
		$this->assertEquals('<div>tset</div>', $this->stripTabs($template->output()->body));
	}
```

**Comment by TomBZombie** [comment]
FYI you can stack formatters:

```php
content: "2015-11-6"; format: date "l", uppercase; //generates"FRIDAY"

```

**Comment by smolinari** [comment]
Ok. If it is to follow CSS conventions, then I guess that will do. Maybe that could still be part of the docs as a "Conventions we are following with Transphporm" section, basically expanding on your point 2? I remember now you explained the CSS convention before and because I am not the best at CSS, what you had told me didn't dawn on me reading the docs. More information about the convention would have pushed me to think I need to understand more about CSS, so TSS conventions make more sense. 

With all that in mind and for my understanding, would this work?
```
$xml = '<ul>
    <li>Name</li>   
</ul>';


$tss = '
    ul li {repeat: blog(users); content: iteration(name);}
';

$blog = ['users' => $users];


$template = new \Transphporm\Builder($xml, $tss);

echo $template->output($blog)->body;
```

Custom formatters looks good.  

Is there a way to do calls on other custom functions?

Scott

**Comment by TomBZombie** [comment]
That currently works, but you need to use the inbuilt `data()` function rather than `blog()`. It's not currently possible to write your own functions, but I'm not sure you'd need to be able to. You can always call `data(myFunction, "arg1", "arg2")` which will call `$data->myFunction('arg1', 'arg2');

**Comment by smolinari** [comment]
So, it would need to be this?
```
$xml = '<ul>
    <li>Name</li>   
</ul>';


$tss = '
    ul li {repeat: data(users); content: iteration(name);}
';

$blog = ['users' => $users];


$template = new \Transphporm\Builder($xml, $tss);

echo $template->output($blog)->body;
```

Hmm....and probably thinking too much again, shouldn't it be more like this?
```
    ul li {repeat: data(blog.users); content: iteration(blog.name);}
```
Scott

**Comment by TomBZombie** [comment]
In short, no. It's impossible with the syntax you're using. There is no way for transphporm to know that the users are related to a `blog`. Where could transphporm read the word "blog" from in the data? 

You could do this:

```php
$xml = '<ul>
    <li>Name</li>   
</ul>';


$tss = '
    ul li {repeat: data(blog.users); content: iteration(name);}
';

$blog = [ 'blog' => ['users' => $users]];


$template = new \Transphporm\Builder($xml, $tss);

echo $template->output($blog)->body;
```

**Comment by smolinari** [comment]
Ah. Ok. Yes. That is simple enough. :+1: 

Sorry, when I am hard of understanding.

Scott
