### ISSUE TITLE
Warning:  file_exists(): File name is longer than the maximum allowed path length on this platform (4096) in /vendors/Transphporm/src/Builder.php on line 101

### ISSUE THREAD

**Issue by jerrywham** [Level-2/Transphporm#190]
To fix this issue, I used that code :
```php
//(line 97)
//Load a template, firstly check if it's a file or a valid string
private function loadTemplate() {
   $result = ['body' => $this->template, 'headers' => []];
   if ($this->isFile($this->template)) $result = $this->loadTemplateFromFile($this->template);
   return $result;
}

private function isFile($filename) {
   return strlen($filename) <= PHP_MAXPATHLEN && is_file($filename);
}
```

**Comment by TomBZombie** [comment]
Thanks, looking at this again here, we can probably speed this up a bit. An `is_file` check here will cause a `stat` internally and require a disk lookup (even if the file doesn't exist). It would be better if we didn't use `is_file` (or the current `file_exists`) unless we know it's a file.

I think a better way might be `strpos($this->template, '<') === false && is_file($this->template)`. It would then only trigger `is_file` when there is no `<` in the template. It's tempting to use `trim($this->template)[0] !== '<' && is_file($this->template)` which would be faster, but we can't guarantee the template starts with a tag. Although most do, `This is a <em>valid</em> template`.

**Comment by jerrywham** [comment]
The commit [9f64d62](https://github.com/Level-2/Transphporm/commit/9f64d621526d7448f0f7e484badd8eebc3b1eb82) doesn't fix the issue. 

Warning is still present.

To fix it, I mixed the two proposition :
```php
    //Load a template, firstly check if it's a file or a valid string
	private function loadTemplate() {
        $result = ['body' => $this->template, 'headers' => []];
		if (strpos($this->template, "\n") === false && $this->isFile($this->template)) $result = $this->loadTemplateFromFile($this->template);
		return $result;
	}

	private function isFile($filename) {
	   return strlen($filename) <= PHP_MAXPATHLEN && is_file($filename);
	}
```

**Comment by TomBZombie** [comment]
Can you show a test case that triggers this error? Surely as of  9f64d62  the only way the warning can appear is if the string is > 4096 characters and doesn't contain a newline character. Surely you don't have a template that's got a single line over 4000 characters?
