### ISSUE TITLE
Caching improvements 

### ISSUE THREAD

**Issue by TRPB** [Level-2/Transphporm#191]
At the moment, Caching works, but all TSS rules get checked frequently.

This is good when you have something like:

```css
main {content: data(model.getPost().articleText); format: markdown; update-frequency: 10m}
```

Which, if `getPost()` goes off and queries the database, then will only perform the query at most once every 10 minutes.

The problem is that it's not based on data. This caches across XML and TSS. If you use different data with the same HTML and tss you need update-frequency: always which means the record is then fetched on every page.

What we need to do is use: Same HTML + Same TSS + Same $data array  as the cache key. This would allow pages for individual articles to be cached.

**Comment by TomBZombie** [comment]
#23e35ef allows for much better caching. I haven't implemented the logic yet but it's now possible to avoid most of Transphporm's code running at all. `Builder::output()` now looks like this:

```php

	public function output($data = null, $document = false) {
		$headers = [];
		$result = $this->loadTemplate();
		$tssCache = new SheetLoader($this->cache,  $this->filePath, $this->tss, $this->time);

		//If an update is required, run any rules that need to be run. Otherwise, return the result from cache
		//without creating any further objects, loading a DomDocument, etc
		if ($tssCache->updateRequired($data) === true) {
			$template = $this->createAndProcessTemplate($data, $result['cache'], $headers);
			$tssCache->processRules($template, $this->config);

			$result = ['cache' => $template->output($document),
			   'headers' => array_merge($result['headers'], $headers),
			   'body' => $this->doPostProcessing($template)->output($document)
			];
			$this->cache->write($this->template, $result);
		}

		unset($result['cache']);
		return (object) $result;
	}
```

If `$tssCache->updateRequired($data)` returns false the entire page's output is returned from the cache as a string without any processing without running any of the rules from the TSS file or loading the XML into a DomDocument object.

The TSS file still has to be loaded (though the tokenized version is loaded from the cache) and we can then work out whether any updates to the XML need to be made in `SheetLoader::updateRequired`. Currently this returns true always but we need some logic for:

1. Have any of the `update-frequencies` expired? E.g. if all rules have `update-frequency: never` then we don't need to process any of the rules and can just return the XML from the cache

2. Is `$data` the same `$data` that was used to 


Still to do:

1. We need to be able to cache based on `$data`  e.g. where `$data->articleText = 'One'` cache the page for that article and have a separate cache for the next article. Or where data contains the id of the logged in user to have a different cached page per user.

2. At the moment we have one cache file per template. There are a finite number of cache files created, if we create a cached version of each XML file with each set of $data we potentially have an infinite number of cache files, we need to be able to expire cached files after a certain amount of time.

**Comment by TomBZombie** [comment]
I played around with various ways of detecting if `$data` has changed since the last load of the template (and creating a different cached version of the template for each $template). Ultimately there's only one feasible way of doing this, but here's what I tried: 

### Option 1: Serialise $data 

I tried `serialize($data)` or `json_encode($data)`. Then we can compare the cached serialized  `$data` to the new `$data` to work out whether `$data` has changed and whether we need to refresh the template. This approach has multiple problems:

1. It doesn't include private properties.
2. If there is any non-serializable object in the `$data` object, it doesn't work.  
3. There may be changed data in `$data` (e.g. timestamps) that isn't used in the template so doesn't require refreshing the template.
4. If the difference in `$data` is a result of a calculation e.g. a method call we can't  know if the template needs refreshing

### (not really an-)Option 2: parse the TSS and check all `data()` calls

We could process the TSS and read any data referenced by `data()` calls, obviously this is self-defeating as it will call and methods in the data object, likely causing database queries.

### Option 3: User-supplied cache key

The only real option requires some user intervention. I've added a `setCacheKey()` function to the template which allows you to do something like this:

```
$template = new \Transphporm\Builder('article.xml', 'showarticle.tss');
$template->setCacheKey($_GET['articleId']);
$template->output($articleModel);
```

This will then create a cached template output for any given `$_GET['articleId']`. This option would also allow things like `$_SESSION['userId']` or `$_SERVER['REQUEST_URI']` as the cache key to cache specific templates per page or per user.

Ultimately, this approach, although not transparent, is more flexible and determining whether we need to load from cache or not is considerably faster.

**Comment by TomBZombie** [comment]
I've basically implemented option 3 from above, but from within the TSS file.

You can do this in the tss:

```css
@cacheKey article.id;

h1, title {content: data(article.title); update-frequency: 30m }
main {content: data(article.id); update-frequency: 30m }
```

Where `$data` is something like

```
[ 'article' => [
   'id' => 1,
   'title' => 'Article 1',
   'content' => 'Article 1  text'
]
]
```


The tss `@cacheKey article.id;` tells TSS to cache based on `article.id`. It creates a cache of the fully rendered template for each unique `article.id`. 


If you request the same article again, it will return the fully rendered template from the cache without needing to do any processing on the template. If you request a different article (with a different id) the template is rendered and cached separately. Next time that article is requested it's loaded from cache.

`update-frequency` is required on every rule for this to work. If `update-frequency` is not set (or set to `always` for a single rule in the tss file, the rule has to be processed and the primary cache is ignored and the following happens:

1. The template is loaded from cache
2. Any rules which have an expired `update-frequency` are executed (any which don't trigger the update still don't get run)
3. The template is rendered and saved back into the cache.


This gives us a very nice approach as if nothing on the page requires updating, the template as a string is just retrieved from the cache without any processing. If something on the page does require updating, the XML is loaded from cache, the update performed and saved back into cache. When the page is loaded again, it either loads from the cache and passes it straight out or does further updates if any other update-frequencies have triggered an update.

**Comment by TomBZombie** [comment]
Cleaning up old files isn't really the job of Transphporm here, that should be handled by the caching layer. I've amended SimpleCache to support garbage collection accordingly: https://github.com/Level-2/SimpleCache

**Comment by TomBZombie** [comment]
I've put a breakdown of how caching works here: https://r.je/transphporm-caching-guide.html

It needs some proper examples and a better structure for the wiki but there's a starting point.

**Comment by TomBZombie** [comment]
Yes you're right, well spotted.

> Also, for consistency's sake, should @cacheKey similarly use data() around non-string keys?

I could superficially make it work, but it has to execute everything after `@cacheKey` on every page load. For performance reasons, I don't want to instantiate the entire `FunctionSet` object which makes the various TSS functions available if we're just checking the cache.

**Comment by garrettw** [comment]
Ok, I didn't realize there was a meaningful difference in the parsing for `@cacheKey`.

One other thing I thought of: would it be useful to allow `update-frequency` to take a value of `never`? I'm imagining a case where I might want to utilize the advanced caching made possible by adding an `update-frequency` to every rule, but some rules aren't dynamic and thus don't need to be updated at all until the TSS file itself changes.

**Comment by TomBZombie** [comment]
`never` is actually already supported, I should add it to the documentation.,

**Comment by thisispiers** [comment]
Has `@cacheKey data(example);` been fully tested? I'm getting a literal cache key of `example`

**Comment by thisispiers** [comment]
Are the following statements correct?

1. `data()` isn't supported in `@cacheKey` when using `\Transphporm\Builder`
2. It's not possible to disable HTML output caching when using `\Transphporm\Builder`
