### ISSUE TITLE
Number formatting fails with passed string data

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#203]
This fails because the argument passed is a string, yet the example in the Wiki documentation uses a literal string and it works.

```php
$xml = '
<h1> </h1>
';

$data['foo'] = "11.234567";

$tss = 'h1 {content: data.foo; format: decimal 2}';

$template = new \Transphporm\Builder($xml, $tss);

echo $template->output($data)->body;
```

**Comment by cxj** [comment]
More specifically, the unit test works because the value argument is a literal string, which PHP no doubt in-_conveniently_ converts to a float, but PHP does not do this automatic conversion for a passed variable.  Here's the unit test code for reference:
```php
public function testFormatNumber() {
		$template = '
			<div>Test</div>
		';;
		$tss = 'div {content: "1.234567"; format: decimal 2;}';
		$template = new \Transphporm\Builder($template, $tss);
		$this->assertEquals('<div>1.23</div>', $this->stripTabs($template->output()->body));
	}
```

**Comment by cxj** [comment]
Since all of my data is coming out of a remote server and stringified over the wire, this is kind of a pain to deal with, unless there's some way TSS could be made to _cast_ a value to a type, e.g. `(float)data.foo;`

**Comment by TomBZombie** [comment]
The issue here is that `data` is not an object in transphporm but a function so it should be:

```php
$tss = 'h1 {content: data(foo); format: decimal 2}';
```

I'm assuming that's just an error in this simplified example, but with  that change, the number is formatted as expected.

**Comment by cxj** [comment]
Ah.  I'll try some more tests.  For what it's worth, here's the real TSS line:
```css
td span.amount {
    content: data(output.claim_result.payer_paid_amount);
    format: decimal 2;
}
```

**Comment by TomBZombie** [comment]
If you want to try to debug it, add a var_dump in `Number.php` and check that the `decimal` function is being passed the value you expect:

```diff
diff --git a/src/Formatter/Number.php b/src/Formatter/Number.php
index fb166fb..9d4946a 100644
--- a/src/Formatter/Number.php
+++ b/src/Formatter/Number.php
@@ -13,6 +13,7 @@ class Number {
        }
 
        public function decimal($num, $decimals) {
+               var_dump($num);
                return number_format($num, $decimals, $this->locale['decimal_separator'], $this->locale['thousands_separator']);
        }
 

```

**Comment by cxj** [comment]
This looks like it is completely my error.  My apologies for the trouble and wasted time.
