### ISSUE TITLE
Repeat on maphper instance

### ISSUE THREAD

**Issue by IamSAB** [Level-2/Transphporm#212]
I try to repeat over a maphper instance which is return by a get method of my model. However nothing is rendered.

For testing i use a simple list as template
```html
<ul>
    <li></li>
</ul>
```
In my tss file 
```
ul li {repeat: data(get); content: iteration(text); }
```
The model is passed directly, so data should be the model
```php
// $view is instance of \Transphporm\Builder, $model is instance of \Model\List
echo $view->output($model)->body;
```
As I understood, data(get) then should call the method below of the model:
```php
// method of \Model\List
public function get(): \Maphper\Maphper
{
   $maphper = $this->maphper;
   // sorting and filtering
   return $maphper;
}
```
As you see, the return instance is a maphper, can that be the problem? Maphper however does not have something like a toArray method and according to my understanding it should act as a normal array.

The output of the foreach loop below shows correct results, thus maphper works correctly.
```php
foreach ($model->get() as $item)
   var_dump($item->id);
   var_dump($item->text);
}
```
```

**Comment by IamSAB** [comment]
Got it, the solution is simple:
```
ul li {repeat: data(get()); content: iteration(text); }
```

**Comment by garrettw** [comment]
Feel free to close this issue then if it's solved. 😃
