### ISSUE TITLE
Transphporm calculates attribute value with / in it instead of passing it as string when using data(myfunction(attr(name)))

### ISSUE THREAD

**Issue by mabalito** [Level-2/Transphporm#214]
Hi,

I'm having this tss:
`include { content: data(getInclude(attr(file))); content-mode: replace; format: html; }`

and this xml:
`<include file="path/tofile.xml"></include>`

Transphporm tries to calculate the attribute (and obviously fails) instead of passing it as a string to my getInclude($file) function. Instead of the expected string "path/tofile.xml" the function receives "NAN".

If I remove "path/" the function receives "xml", so there's also some weird behaviour with attribute values with a "." in it. Weirdly, Transphporm doesn't try to calculate attribute values with a "-" in it, so it's very inconsistent.

I would expect the value to get passed as-is, i.e. as a string.

Thanks in advance

**Comment by garrettw** [comment]
If I'm not misunderstanding, the readme [indicates](https://github.com/Level-2/Transphporm#2-use-data-to-describe-the-relevant-parts-externally) that you would do this with the following TSS:
```css
include { content: template(attr(file)); content-mode: replace; format: html; }
```

**Comment by mabalito** [comment]
Yes, that would have worked for me if it weren't for #213 and #215.

What I instead have come up with is a function that creates a new \Transphporm\Builder instance and returns the output to the "parent" view.

Also, I don't see why attr() should behave differently when it's used in data() and template(). It should be consistent in my opinion.

Btw, thanks for a great project!

**Comment by TRPB** [comment]
This is treating the value as a division. Unfortunately this is the same issue as #221, and a rather large job as it will require rewriting a lot of the parser. I'm glad you've got a workaround  in this instance so I'll close this for now, but keep an eye on #221 as I'll update that when I recreate the parser.

**Comment by TRPB** [comment]
This should be fixed in the latest commit to master. #213 and #215 still need addressing though.
