### ISSUE TITLE
Nested loop/foreach

### ISSUE THREAD

**Issue by IamSAB** [Level-2/Transphporm#216]
I got the following data to render a table. Columns gives info about the data to render. If rows is a Maphper instance I define with the columns data what columns to show of a specific database table.

```php
$data = [
    'columns' => [
        'id' => 'Id',
        'name' => 'Name'
    ],
    'rows' => [
        [
            'id' => 0,
            'name' => 'Peter'
        ],
        [
            'id' => 1,
            'name' => 'Tony'
        ],
        [
            'id' => 2,
            'name' => 'Rahel'
        ]
    ]
];
```

With classic php templating the table body would be rendered like this:
```php
echo '<tbody>';
foreach ($data['rows'] as $row) {
    echo '<tr>';
    foreach ($data['columns'] as $name => $label) {
        echo '<td>' . $row[$name] . '</td>';
    }
    echo '</tr>';
}
echo '</tbody>';
```
However, I can not find a way, to achieve the same result with transphporm. It seems not possible to use data of a parent iteration:
```php
$xml = "
    <table>
        <thead>
            <tr>
                <th>Head</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Body</td>
            </tr>
        </tbody>
    </table>
";

$tss = "
    table thead tr th { repeat: data(columns); content: iteration() }
    table tbody tr { repeat: data(rows) }
    table tbody tr td { repeat: data(columns); content: iteration(key()) } // what to write here?
";

$template = new \Transphporm\Builder($xml, $tss);
echo $template->output($data)->body;
```
Has somebody a hint?

**Comment by solleer** [comment]
Try
```
$tss = "
    table thead tr th { repeat: root(columns); content: iteration() }
    table tbody tr { repeat: root(rows); bind: iteration(); }
    table tbody tr td { repeat: root(columns); content: data(key()); }
";

**Comment by IamSAB** [comment]
Great, that works. 
Can you please explain further the root() method and the bind property and their usage. Just the solution itself helps not very much in understanding Transphporm.
Or is there already a wiki page about the two features?

**Comment by solleer** [comment]
The root method navigates the data starting from the base of the tree that is passed into Transphporm. The bind property sets the base that the data function navigates from for that element and all children elements.

For example:
```php
$xml = "
<div>
    <h1></h1>
    <p></p>
</div>
";

$tss = "
    div { bind: data(test); } // root(test) would also work
    div h1 { content: data(child); } // content will be 'stuff'
    div p { content: root(test.child); } // content will be 'stuff'
";

$data = [
    'test' => [ 'child' => 'stuff' ]
];

$template = new \Transphporm\Builder($xml, $tss);
echo $template->output($data)->body;

**Comment by IamSAB** [comment]
Thanks for the explanation. Learned something more :D

**Comment by jpeurich** [comment]
It is great to know about the "root" method and "bind" property.  But, how did you know about them?  I can't find any documentation about them. What other non-documented Transphporm gems are available, and how does one find out about them?

**Comment by solleer** [comment]
I created the root method in #94 and #96 and at some point Tom mentioned the bind property so I have always known about it. There definitely should be some more documentation added to the wiki.
