### ISSUE TITLE
Alter <option> selected without enumerating all options

### ISSUE THREAD

**Issue by cj-clx** [Level-2/Transphporm#219]
I need some way to target one `<option>` in a `<select>` list as `selected` based upon data containing only the selected option value (or ID).  There does not seem to be a way to select an option other than to enumerate every possible `<option value=...>` in my TSS, which is impractical for large lists and defeats the ability to have something like a dynamic array of data provide the valid options.

Here's what I'd like, or something similar.  Or if there's a way to do this already, I'd love some guidance on how to do so.  Note the `option[value=data(option)]:attr(selected)` line.
```php
<?php
require "vendor/autoload.php";

$xml = <<<XML
    <select>
        <option value="one">One</option>
        <option value="two">Two</option>
        <option value="tre">Three</option>
    </select>
XML;
$tss = <<<TSS
option[value=data(option)]:attr(selected) {
    display: "selected";
}
TSS;

$data["option"] = "two";

$template = new Transphporm\Builder($xml, $tss);
$output = $template->output($data)->body;
echo $output . PHP_EOL;
```

**Comment by TRPB** [comment]
Take a look at 3783997e390626ff26f0b158b2f77138ce498fd9 , this is now supported.

It's a bit of a pain because

```css
.status option:attr(value) {
    content: key();
}
```

gets run on the kept element (that normally would be replaced with a valid iteration from `$data`). 

Internally, elements can now be flagged with the attribute `transphporm="immutable"` which prevents any rules running on them.

**Comment by cj-clx** [comment]
I'll try it out as soon as I can.

**Comment by TRPB** [comment]
Sorry, I didn't realise this was a different issue. This fixes the problem with the default option  being removed.

**Comment by cj-clx** [comment]
Even better.  I wonder why I didn't think of trying that myself.  I will add it to the wiki.
