### ISSUE TITLE
Linefeed causes Exception

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#220]
In the following code, the linefeed (or line break) between `attr` and `(selected)` causes an `\Exception` to be thrown:
```php
<?php
require "vendor/autoload.php";

$xml = <<<XML
    <select>
        <option value="one">One</option>
        <option value="two">Two</option>
        <option value="tre">Three</option>
    </select>
XML;

$tss = <<<TSS
option[value=data(option)]:attr
(selected) {
    content: "selected";
}
TSS;

$data["option"] = "two";

$template = new Transphporm\Builder($xml, $tss);
$output = $template->output($data)->body;
echo $output . PHP_EOL;
```

If the line break is made after the paren, it works correctly.  This came about as a result of my editor doing an automatic line wrap.

It would be nice if the tokenizer was able to be white-space insensitive, but I've not examined the grammar closely to know if that's globally possible.

**Comment by TRPB** [comment]
Unfortunately whitespace sometimes has meaning (e.g. `div .someclass` is different to `div.someclass`  ) so we have to work around it. I'll try to apply a fix.
