### ISSUE TITLE
Unit tests fail under PHP 7.4.3

### ISSUE THREAD

**Issue by cj-clx** [Level-2/Transphporm#226]
The `phpunit` tests fail in what looks like to be more than one way when run under PHP 7.4.3.  At least one class or group of the failures appears to be a result of strict type checking:
```
96) TransphpormTest::testDataFunctionReturnFalse
Trying to access array offset on value of type bool
```

**Comment by cj-clx** [comment]
Also, something odd going on with time comparisons.  Here is "seconds" but the minutes and hours tests fail similarly.
```
1) DateFormatTest::testSecondsin
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'in 33 seconds'
+'in 32 seconds'
```

**Comment by cj-clx** [comment]
I will investigate further, and report anything further useful.  Also, I or you can break up this issue into separate issues for each test and failure, if you like.

**Comment by TRPB** [comment]
The time test is because time now includes microseconds so comparing seconds will always fail.

**Comment by cxj** [comment]
My bad.  The only real error is this one:
```
1) DateFormatTest::testWeeksin
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'in 2 weeks'
+'in 13 days'
```

**Comment by cj-clx** [comment]
I'll open a new ticket for the one real error.
