### ISSUE TITLE
included templates doesn't get wrapped in <template>

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#25]
Hi,

I did something like this:

I had a main html file with an empty ```<head>``` tag, which I then filled with

```
head {
  content: template("includes/Admin\Head.html");
}
```
Admin\Head.html was just the usual stuff like

```html
<meta charset="utf-8" />
<title>Title</title>
```
Then I got a warning:
```
Warning:  DOMDocument::loadXML(): Extra content at the end of the document in Entity
```
Which is quite logic, as the DOMDocument couldn't find a root element. Usually transphporm wraps xml in a ```<template>``` tag, but not xml from a file as it looks in Builder.php:35
```php
$template = new Template($this->isFile ? $this->template : '<template>' . $this->template . '</template>');
```

I'm not sure if this is wanted behaviour.

Cheers,
Martin

**Comment by smolinari** [comment]
I believe any file content should be wrapped in a `<template>` tag. Like so:


**header.xml**
```
<?xml version="1.0"?>
<template>
    <meta charset="utf-8" />
    <title>Title</title>
</template>
```

Scott

**Comment by TomBZombie** [comment]
This needs updating, the problem initially is that 

```
<meta charset="utf-8" />
    <title>Title</title>
```

On its own is not valid XML. The rule needs to be either the template needs to be a valid XML file (with a root element) or it needs to be wrapped in <template> tags. I need to do some tests/tweaks for this as the behavior is different for files and strings.

**Comment by TomBZombie** [comment]
I've updated this to work in a better way. It now acts identically for files and strings.

Templates are wrapped in `<template>` tags if there is no `<!DOCTYPE` or `<?xml` declaration. If you supply a file/string with a doctype or XML declaration it's treated as an entire document, rather than a partial.

**Comment by smolinari** [comment]
Good solution Tom. :+1: 

Scott
