### ISSUE TITLE
just one @import possible

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#26]
As the title states, it looks like it's just possible to import one .tss file. But I could'nt figure out why.

Cheers,
Martin

**Comment by TomBZombie** [comment]
Thanks, I've fixed this. It worked if the import lines were separated by another rule:

```
@import 'file1.tss';
div {content: "foo";}
@import 'file2.tss';
``

But not when there were two together:

```
@import 'file1.tss';
@import 'file2.tss';
div {content: "foo";}
``

I've fixed the import script so it works as expected :)

**Comment by hobbeshunter** [comment]
Thanks a lot
