### ISSUE TITLE
Caching - WIP

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#27]
I've added some very early support for caching. The intention is to allow for this:

```php

div {content: data(readFromDb); update-frequency: 10m}
```

Where `update-frequency` takes a time value `10m` being 10 minutes, `2d` being 2 days and `30m` being 30 minutes, `10s` being 10 seconds, etc.

It also supports `never` meaning that once the page is generated it's never updated again. As well as `always` which is the default which means that the content is *always* updated.

The way this works is that it generates the XML page and saves the final generated XML. When `content` is run again, the original content of the node is replaced. `update-frequency` when combined with `content` will only do the replacement when the time limit is up. 

By making this value specific to rules it allows refreshing different parts of the page at different speeds, as well as adding a delay to intensive operations. Because of this, you should always pass *models* as `data` so that the functions that retrieve information from the database are only called when they are needed. One of the biggest problems with "template caching" in current systems is that it only caches the display logic, the data is still retrieved from the database which is almost always a bigger bottleneck than looping over the results and generating the HTML.

To use the cache, assign a class that implements `ArrayAccess` to the builder using

```php
$cache = new \ArrayObject;
$template = new \Transphporm\Builder($xml, $tss);
$template->setCache($cache);
```

I suggest using simplecache: https://github.com/Level-2/SimpleCache which will write to files. You can obviously implement a memcache version by using the `ArrayAccess` interface.

e.g.

```php
$cache = new \SimpleCache\SimpleCache('./cache-dir');
$template = new \Transphporm\Builder($xml, $tss);
$template->setCache($cache);
```

### Please note: Caching only works when loading TSS and XML from files.

Currently there are several things to implement:

- [x] TSS files are only parsed when they are updated
- [x] Support for `never` and `always`
- [x] Support for durations e.g. `10m`
- [x] Support for `repeat`. Currently if an element is repeated, it is cached and the next time the template is generated, it will just append the new results. There needs to be some way of storing the *original* value and then hiding it from the final outcome
- [x] Support for `display: none` At the moment, if this rule is run conditionally and it hides the element once, it will be hidden forever, even if next time the data says it should not be hidden.

For `display` and `repeat` there will need to be some post-processing which runs after the output has been saved.

**Comment by smolinari** [comment]
Sounds good Tom. :+1: 

Scott

**Comment by hobbeshunter** [comment]
Hi Tom,

looks great. So great that I had to try it with SimpleCache. Anyway, a few questions came up.

1. I don't get line 65 in Builder.php
```php
$key = $this->tss . $template->getPrefix() . $this->baseDir;
```
it produces stuff like
```
/var/www/html/<dir>/tmp/templates/Admin\Authentification\main.tss/var/www/html/<dir>/templates/
```
2. SimpleCache want's to have directorys, but doesn't want to create them. In my case "templates".
3. When I echo the ```$key``` everytime ```write()``` in FileCache.php is called, it looks like Transphporm tries to write down everything twice. Is this necessary?

**Comment by TomBZombie** [comment]
> I don't get line 65 in Builder.php

This is the cache key, you're right this should be MD5'd so that it works with file names. The key is based on the TSS filename, the directory it's stored in and the template it's applied to. This is required as the rules are different if you're using a template with a xml namespace. 


> When I echo the $key everytime write() in FileCache.php is called, it looks like Transphporm tries to write down everything twice. Is this necessary?

Well spotted, I've removed the second write :)

**Comment by hobbeshunter** [comment]
Thanks a lot!

**Comment by TomBZombie** [comment]
Caching now also supports repeated elements

TODO: Add documentation for caching
