### ISSUE TITLE
Error reading doctype

### ISSUE THREAD

**Issue by williamokano** [Level-2/Transphporm#29]
Hi, I was testing you template tool (and by the way, seems fantastic your approach) and I created a very simple template:

```
<!DOCTYPE HTML>
<html>
    <head>
        <title>Just a test</title>
    </head>
    <body>
        <h1>Hello World</h1>
        
        <h2>Devs</h2>
        <ul>
            <li>Cristiano</li>
            <li>Leonardo</li>
            <li>William</li>
        </ul>
    </body>
</html>
```

If I use ```<!doctype html>``` instead of  ```<!DOCTYPE HTML>```  (or any variation but the doctype has the be lower case) it will trigger the following error:

```

Warning: DOMDocument::loadXML(): StartTag: invalid element name in Entity, line: 1 in C:\Users\williamokano\Desktop\teste\vendor\level-2\transphporm\src\Template.php on line 19

Warning: DOMDocument::loadXML(): Extra content at the end of the document in Entity, line: 1 in C:\Users\williamokano\Desktop\teste\vendor\level-2\transphporm\src\Template.php on line 19

Notice: Trying to get property of non-object in C:\Users\williamokano\Desktop\teste\vendor\level-2\transphporm\src\Template.php on line 22

Notice: Trying to get property of non-object in C:\Users\williamokano\Desktop\teste\vendor\level-2\transphporm\src\Template.php on line 66

Notice: Trying to get property of non-object in C:\Users\williamokano\Desktop\teste\vendor\level-2\transphporm\src\Template.php on line 66
```

According to this link of [http://www.w3.org/TR/html5/syntax.html#the-doctype](http://www.w3.org/TR/html5/syntax.html#the-doctype) W3C, the doctype is case-insensitive, so it should not trigger an error.

Nice project, have good expectations about it and sorry about the bad english.

**Comment by williamokano** [comment]
Well, since I can't delete issues, I'll just mark it as duplicated of #8 .

Although I think this should be fixed (It´s not hard to, just change the validation to some ignored-case regex.

My bad!

**Comment by TomBZombie** [comment]
Unfortunately this is a limitation of PHP's DomDocument class. If you use a lowercase doctype it will cause an error.

One potential fix for this is running str_replace() on the doctype when a template is added. The downside of this is that the doctype will be uppercase in the final output.

**Comment by williamokano** [comment]
Hi @TomBZombie I think that using str_replace would only causes an unnecessary overhead. I suggested to use regex but this would create also an unnecessary overhead, so I think that the "best" solution, at least for this moment, is to replace all the lowercase doctypes for uppercase doctypes.

**Comment by TomBZombie** [comment]
I've added a simple str_replace. The overhead is going to be minimal in this case and it will lead to less confusion in the future.

**Comment by williamokano** [comment]
Ok thanks @TomBZombie :) I appreciate!
