### ISSUE TITLE
Conditionals on TSS

### ISSUE THREAD

**Issue by williamokano** [Level-2/Transphporm#30]
Hi, I was wondering if you will apply (or how to do) some conditional into the TSS rules.

For example, I would like do something like that on Transphporm (the syntax is from Laravel Blade)

```
    @if($datatable['ajax'])
        @include('crud.datatable.ajax_options')
    @endif
```

Is it possible today? And don´t mind with the include, pretend that is some plain html

**Comment by TomBZombie** [comment]
You can apply conditional by conditionally targetting an element there is an example here: https://github.com/Level-2/Transphporm#conditionally-applying-http-headers but you're right that it's not clear and I'll provide better documentation.

You can inspect `$data` using:

```css
element:data[foo=bar] { /* rules */ }
```

And the rules will only be applied to that element when the condition is met. For example,

```php
$data = [
 'loggedIn' = true;
];

$xml = '
<div class="loggedin">
Welcome back, you are logged in
</div>

<div class="notloggedin">
You are not logged in, please click here to log in
</div>';

$tss = '
.loggedin:data[loggedin=false] {display: none; }
.notloggedin[loggedin=true] {display: none; }
';
```

Which will conditionally show/hide the relevant block depending on whether $data['loggedin'] is true or false.

**Comment by williamokano** [comment]
Got it, I tried here and theres a little mistake, here's the "fixed" version working:

**index.php**
```
<?php
require_once "vendor\autoload.php";

use Transphporm\Builder;

$xml = file_get_contents("index.html");
$tss = file_get_contents("index.tss");

$data = [
    'loggedin' => true,
    'users' => [
        'william', 'thiago', 'cristiano', 'leonardo'
    ]
];

$template = new Builder($xml, $tss);

echo $template->output($data)->body;
```

**index.html**
```
<!DOCTYPE html>
<html>
    <head>
        <title>Conditional Example</title>
    </head>
    <body>
        <div class="loggedin">
            Welcome back, you are logged in
        </div>

        <div class="notloggedin">
            You are not logged in, please click here to log in
        </div>
        
        <ul>
            <li></li>
        </ul>
    </body>
</html>
```

**index.tss**
```
.loggedin:data[loggedin=false] {display: none; }
.notloggedin:data[loggedin=true] {display: none; }
ul li {repeat: data(users); content: iteration(); }
```

Well done (and thanks for blazing fast answer)

**Comment by TomBZombie** [comment]
One small note, you don't need this code:

```php
$xml = file_get_contents("index.html");
$tss = file_get_contents("index.tss");
```

Transphporm automatically works out whether it's been given a filename or a string, you can just use:

```php

$template = new Builder('index.html', 'index.tss');
```

instead :)

**Comment by williamokano** [comment]
Ok, thanks again, note taken :)
