### ISSUE TITLE
Selector

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#31]
Can a way to compare attribute selectors and passed data be added
Something like this
`element[attr=data()] { display: none; } `

One reason for this is to set the default value for a select field or radios in a form

**Comment by TomBZombie** [comment]
This is a very good idea, I'll implement this shortly :)

**Comment by TomBZombie** [comment]
This took quite a few changes, but in general for the better as I had to split the code up in a way that makes more sense.

**Comment by solleer** [comment]
Thank you so much
