### ISSUE TITLE
display: none on attributes

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#36]
I think it would be nice to have something like
```
#PagesEditFormPublishedInput:attr(checked):data(published=false) {
  display: none;
}
```

**Comment by TomBZombie** [comment]
For filtering rather than selecting, you can use

`:attr[checked=checked]:data[published=false] `

**Comment by TomBZombie** [comment]
Try that :) 

If you're reading data you'll need to use `:data[published=false]` with square brackets. This is from CSS, things like `:nth-child(1)` use round brackets and filtering based on value e.g. `[attr=value]` uses square brackets.

**Comment by hobbeshunter** [comment]
Beautiful :)
