### ISSUE TITLE
make content accessible through a variable

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#37]
Wouldn't it be nice to have a content() variable?
So
```
#selector {
  content: content(), 'test';
}
```
would append ```test``` to it.

**Comment by TomBZombie** [comment]
Youb can do this using selector:after :)

**Comment by hobbeshunter** [comment]
Thanks

**Comment by hobbeshunter** [comment]
But there is another problem:
Catchable fatal error: Object of class DOMElement could not be converted to string in /var/www/html/eckblick/eckframe/trunk/vendor/level-2/transphporm/src/Property/Content.php on line 58

**Comment by TomBZombie** [comment]
Can you paste your code?

**Comment by hobbeshunter** [comment]
I think the problem is here:
```
  <head>
    <script src='https://cdn.tinymce.com/4/tinymce.min.js'></script>
    <script src="js/admin.js"></script>
  </head>
```
I have a standard head.html which usually insert in every page. But then some pages have some extra JavaScript. So I thought
```
head:before {
  content: template("templates/Admin/includes/Head.html");
}
```
would do the job. But at some point Transphporm fails to proberly insert the  ```<script>``` tags.

**Comment by TomBZombie** [comment]
:before and :after were not set up to use template() and were expecting strings, I've accounted for it.
