### ISSUE TITLE
How to insert xml from the data object?

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#38]
I'm trying to insert some xhtml generated by TinyMCE and stored in a database (a little CMS). But Transphporm just inserts this like a string and browsers don't render it properly. Maybe ```content-type: [string/xml]``` could be a solution.

**Comment by TomBZombie** [comment]
you can use `content: "<b>Foo</b>"; format: html;` to convert the content to HTML. However, a slight caveat is that currently it must be valid XHTML.

**Comment by hobbeshunter** [comment]
oh thanks. didn't know about ```format: html```
