### ISSUE TITLE
displaying none and displaying block

### ISSUE THREAD

**Issue by StuTheBearded** [Level-2/Transphporm#39]
I'm currently trying to work out how to do inline error messages using a data attribute to select the correct error message, here is my HTML and TSS.

    <div class="fieldset">
        <label for="email">form-email <small>field-required</small></label>
        <span><input name="email" id="email" type="text" value=""/></span>
        <p class="field-error" data-for="email"></p>
    </div>
    <div class="fieldset">
        <label for="confirmemail">form-confirmemail <small>field-required</small></label>
        <span><input name="confirmemail" id="confirmemail" type="text" value=""/></span>
        <p class="field-error" data-for="confirmemail"></p>
    </div>

.fieldset { bind: data(formData) }
.fieldset input:attr(value) {content: data(attr(name)); }
.field-error { display:none; }
.field-error {
    content : data(formErrors[attr(data-for)]);
    display:block;
}

$data = new stdClass;
$data->formData = ['email' => 'someone@something.org', 'confirmemail' => 'someone@something.com'];
$data->formErrors = ['confirmemail' => 'Your emails don\'t match'];

$template = new Transphporm\Builder("templates/page.xml", 'templates/register.tss');
echo $template->output($data)->body;

I can get transphporm to either hide all the .form-error p's or display them all but not hide the empty. When they all display however never have any data so I assume i'm doing something wrong with that. But it might be nice to have something like the empty selector so then I can do.

.form-error:empty { display:none; }

**Comment by TomBZombie** [comment]
This actually ties into another issue I posted about validation. What we really need is an in_array selector:

```
.field-error:attr(data-for):in[data(formErrors]) { content : data(formErrors[attr(data-for)]); }
```

I'm not sure that's the best way to express it but something like that would solve quite a few problems

**Comment by TomBZombie** [comment]
Actually a better way would be an operator so we can use it as a filter. Currently this will work:

```
:data[error=attr(data-for);
```

Which will work if `data(error)` is a single value. What's really needed is an array lookup:

```
:data[errors[attr(data-for)]] 
```

Which would solve it in a much simpler and more versatile way.

**Comment by TomBZombie** [comment]
Also, take a look at https://github.com/Level-2/Transphporm/issues/34 Transphporm will be handling validation as well :)

**Comment by StuTheBearded** [comment]
:data[errors[attr(data-for)]] 

Hmmm I like the idea for the in array checks would greatly improve flexibility when displaying items especially form errors and that would also go a long way to helping solve premissions based templates too the data isn't there simply don't display it.

The validation is interesting one though I'm not sure the templating engine handling validation, I did something a while back with XHTML so that xml parser would run accross a form and with a few extra attributes in the html to work out how the validation rules compile a bunch of objects to handle it. Eventually I separated the validation rules from the form as it was less likely that someone could accidentially break the validation while editing HTML.

If you added some sort of class mapping where you could say for this type of validation in the TSS say "required" that maps to a required class and TSS uses that in conjuction with dice for loading validation dependancies like db connections if validation requires that.

**Comment by TomBZombie** [comment]
I've just added support for this. See the following two unit tests:

```php

	public function testFilterDataArray() {
		$data = [
			'anArray' => [
				'one' => 'foo',
				'two' => 'bar'
			]
		];

		$xml = '
		<div class="one">

		</div>
		<div class="two">

		</div>
		<div class="three">
		</div>
		';

		$tss = 'div:data[anArray[attr(class)]] {content: data(anArray[attr(class)]) }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs($template->output($data)->body), $this->stripTabs('
			<div class="one">foo</div>
			<div class="two">bar</div>
			<div class="three">
			</div>
		'));;

	}

	public function testFilterDataArrayWithEquals() {
		$data = [
			'anArray' => [
				'one' => 'foo',
				'two' => 'bar'
			]
		];

		$xml = '
		<div class="one">

		</div>
		<div class="two">

		</div>
		<div class="three">
		</div>
		';

		$tss = 'div:data[anArray[attr(class)]="foo"] {content: data(anArray[attr(class)]) }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs($template->output($data)->body), $this->stripTabs('
			<div class="one">foo</div>
			<div class="two"></div>
			<div class="three">
			</div>
		'));;

	}


```

**Comment by TomBZombie** [comment]
This is now supported, see these two unit tests for examples:

```php
public function testFilterDataArray() {
		$data = [
			'anArray' => [
				'one' => 'foo',
				'two' => 'bar'
			]
		];

		$xml = '
		<div class="one">

		</div>
		<div class="two">

		</div>
		<div class="three">
		</div>
		';

		$tss = 'div:data[anArray[attr(class)]] {content: "set" }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs($template->output($data)->body), $this->stripTabs('
			<div class="one">set</div>
			<div class="two">set</div>
			<div class="three">
			</div>
		'));;

	}

	public function testFilterDataArrayWithEquals() {
		$data = [
			'anArray' => [
				'one' => 'foo',
				'two' => 'bar'
			]
		];

		$xml = '
		<div class="one">

		</div>
		<div class="two">

		</div>
		<div class="three">
		</div>
		';

		$tss = 'div:data[anArray[attr(class)]="foo"] {content: data(anArray[attr(class)]) }';

		$template = new \Transphporm\Builder($xml, $tss);

		$this->assertEquals($this->stripTabs($template->output($data)->body), $this->stripTabs('
			<div class="one">foo</div>
			<div class="two"></div>
			<div class="three">
			</div>
		'));;

	}
```

**Comment by StuTheBearded** [comment]
Ok so that all works as long as you haven't used bind: on a parent tag took me about 20mins to figure that one out. It does mean now I can have a sort style sheet mix-in for handling forms

**Comment by TomBZombie** [comment]
Perhaps we need parentData() or rootData() functions that allow reading the raw data. I'm not sure how useful this is though, if you've bound data to a parent element I'd expect that to be what you'd need for child elements. Especially in the case of forms where you'd bind `$_POST`
