### ISSUE TITLE
Pronounciation?

### ISSUE THREAD

**Issue by OnkelTem** [Level-2/Transphporm#42]
I really want to know how it is supposed to pronounce "Transphporm"?
Transf-porm? Well...

The same question is about Maphper. Is it like Maf-per?

**Comment by smolinari** [comment]
The "h" is silent in Maphper, so like "mapper" and the second "p" is silent in Transphporm, like Transform.

Well, at least that is how I say them. :smile: 

Scott

**Comment by OnkelTem** [comment]
:+1:
