### ISSUE TITLE
Pass argument to data

### ISSUE THREAD

**Issue by hobbeshunter** [Level-2/Transphporm#43]
Is it possible to pass an argument to the data object?

I'm currently building a small CMS and the Admin can build and edit menus. Furthermore there is a spot marked in the template for e.g. "primaryMenu". Then I want the model to return the "primary menu" So I want something like:
```
ul.primary li {
  repeat: data(menuItems(primary));
}
```

**Comment by TomBZombie** [comment]
This was actually just added, see #41

**Comment by hobbeshunter** [comment]
Great. I'm too lazy to read every thread ;)

**Comment by TomBZombie** [comment]
No worries! I've only done some basic tests so far, let me know if something doesn't quite work correctly!

**Comment by hobbeshunter** [comment]
```
.menu ul li {
  content: data(menuItems('primary'));
}
```
creates this error:
```
 Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /var/www/html/.../vendor/level-2/transphporm/src/Parser/Value.php on line 89
```

**Comment by solleer** [comment]
I get that same error when I don't send any arguments

**Comment by TomBZombie** [comment]
That error is now fixed.
