### ISSUE TITLE
Css to Xpath

### ISSUE THREAD

**Issue by VincentClair** [Level-2/Transphporm#49]
Hello,

I have seen you have developped a class to convert css to xpath.
I also seen an existing one in Symfony : https://symfony.com/doc/current/components/css_selector.html.
Will it be interesting to use it and reduce maintenance needed in Transphporm ?

**Comment by TomBZombie** [comment]
After a quick look it really seems like overkill for transphporm, the CSS to xpath class in transphporm does what's needed here in 100 lines, it's not really worth a dependency on a library over 10 times that
