### ISSUE TITLE
Path for Partials should be relative to parent.

### ISSUE THREAD

**Issue by Pixelfck** [Level-2/Transphporm#52]
When trying to include a partial into a template, I get error message:

> **Warning**: filemtime(): stat failed for nav.xml in **...\vendor\level-2\transphporm\src\Builder.php** on line **85**
> 
> **Warning**: file_get_contents(nav.xml): failed to open stream: No such file or directory in **...\vendor\level-2\transphporm\src\Builder.php** on line **86**

I would expect the path for partials to be relative to their parent by default. Is this a bug, an oversight or intended behaviour?
In any case, I think it would be most helpful if the path for files to pull in (either .xml or .tss), was always calculated relatively to the parent file, because the .tss file should not have to know about the location of the .php script by which it was used.

Directory structure
~~~
app
  |- views
  |    `- index.php
  `- templates
       |- index.tss
       |- index.xml
       `- nav.xml
~~~

File: index.php
~~~php
<?php
// ... Autoloading, etc excluded for clarity ...

use Transphporm\Builder AS TransphpormBuilder;

$xml = __DIR__.'/../templates/index.xml';
$tss = __DIR__.'/../templates/index.tss';

$template = new TransphpormBuilder($xml, $tss);

echo $template->output($data)->body;
~~~

File: index.xml
~~~xml
<html>
	<div id="nav">
		<ul>
			<li><a href="#">Menu Item</a></li>
		</ul>
	</div>
</html>
~~~

File: index.tss
~~~css
#nav {
	content: template('nav.xml');
}
~~~

File: nav.xml
~~~xml
<ul>
	<li><a href="foo.php">Foo</a></li>
	<li><a href="bar.php">Bar</a></li>
</ul>
~~~

**Comment by solleer** [comment]
THe problem is that the thing that sets baseDir is run after the DataFunction is created

**Comment by TomBZombie** [comment]
Well spotted, I've added a quick workaround for this, although it could be tidier this should work. I'm going to change the way BaseDir's are handled but for now this  will solve the issue.

**Comment by joaoeduardo** [comment]
This error has been corrected?

**Comment by solleer** [comment]
Correct

**Comment by joaoeduardo** [comment]
I asked because I had this error while developing a theme for wordpress. I am using [roots/bedrock](https://github.com/roots/bedrock) boilerplate, but I am building from scratch the theme. Bellow follows my code:

Folder structure:

```
theme/
├── bower.json
├── build
├── composer.json
├── composer.lock
├── gulpfile.js
├── index.php
├── package.json
├── source
│   ├── assets
│   │   ├── fonts
│   │   ├── images
│   │   ├── scripts
│   │   └── styles
│   └── views
│       ├── home.tss
│       ├── home.xml
│       └── layout.xml
└── style.css
```

index.php

```php
<?php

global $wp_query;

$template = new \Transphporm\Builder(
    get_template_directory() . '/source/views/layout.xml',
    get_template_directory() . '/source/views/home.tss'
);

echo $template->output($wp_query->get_posts())->body;
```

layout.xml

```xml
<!DOCTYPE HTML>
<html lang="pt-br">
  <head>
    <meta charset="utf-8"/>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Title</title>
    <!-- build:css styles/app.css -->
    <!-- bower:css -->
    <!-- endbower -->
    <link href="build/assets/styles/main.css" rel="stylesheet"/>
    <!-- endbuild -->
  </head>
  <body>Content</body>
</html>
```

home.tss

```css
title {
  content: "My Site"
}

body {
  content: template("/home/vagrant/Code/wordpress/wwwroot/app/themes/polarfix-theme/source/views/home.xml")
}

ul li {
  repeat: data(0);
  content: iteration(post_title);
}
```

home.xml

```xml
<?xml version="1.0"?>
<template>
  <ul>
    <li>Post</li>
  </ul>
</template>
```

If I put only `home.xml`, I get the same error.

**Comment by solleer** [comment]
What is the error

**Comment by joaoeduardo** [comment]
```
Warning: filemtime(): stat failed for home.xml in /home/vagrant/Code/wordpress/vendor/level-2/transphporm/src/Builder.php on line 85

Warning: file_get_contents(home.xml): failed to open stream: No such file or directory in /home/vagrant/Code/wordpress/vendor/level-2/transphporm/src/Builder.php on line 86
```

**Comment by solleer** [comment]
I don't think the release on packagist has been updated

**Comment by joaoeduardo** [comment]
I will try to install from github.

**Comment by joaoeduardo** [comment]
Sorry. Installing through github worked. Thank you.

**Comment by solleer** [comment]
Soon I think he plans to make a 1.1 release so the packagist version will probably be up to date then. The new parser will hopefully be added then too.
