### ISSUE TITLE
@import not supporting Transphporm's `data()` function

### ISSUE THREAD

**Issue by Pixelfck** [Level-2/Transphporm#53]
When trying to `@import` using Transphporm's `data()` function, I get the following error:

> **Warning**: file_get_contents(D:\WWW\framework\app\templates\data(contentTss)): failed to open stream: No such file or directory in **...\vendor\level-2\transphporm\src\Sheet.php** on line **71**

File: index.php
~~~php
<?php
// ... Autoloading, etc excluded for clarity ...

use Transphporm\Builder AS TransphpormBuilder;

$xml = 'index.xml';
$tss = 'index.tss';

$template = new TransphpormBuilder($xml, $tss);

$data = [foo => 'bar.tss'];

echo $template->output($data)->body;
~~~

File: index.xml
~~~xml
<html><body>hello, world</body></html>
~~~

File: index.tss
~~~css
@import data(foo);
~~~

**Comment by TomBZombie** [comment]
I've just added support for this :)
