### ISSUE TITLE
BUG: nth-child(n) broken!

### ISSUE THREAD

**Issue by Pixelfck** [Level-2/Transphporm#54]
There is a bug in  `nth-child(n)`, because of which only nth-child(2) is interpreted and then proceeds to fill all the elements as if no Pseudo-element was used.
All other (non 2 value) `nth-child()` calls are ignored.

The example as described in [Basic Usage: Loops#Simple one dimensional arrays](https://github.com/Level-2/Transphporm/wiki/Basic-Usage:-Loops#simple-one-dimensional-arrays) showcases the problem, as do some of the other examples which have to do with tables.

**Comment by solleer** [comment]
This is the string I get when I `var_dump($element->getNodePath())` in \Transphporm\Pseudo\Nth
`/html/body/div/main/div[1]/form/a[2]`
The bracket parser reads the first bracket and not the second one which is what it is being used on

**Comment by solleer** [comment]
I think I fixed it with #58

**Comment by TomBZombie** [comment]
Thanks for fixing this @solleer , I've added some additional test cases to prevent this being broken again.
