### ISSUE TITLE
BUG: Iframes

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#55]
Iframes do not seem to work. It gives the error

> Warning: DOMDocument::loadXML(): EntityRef: expecting ';' in Entity, line: 3 in C:\Users\admin\OneDrive\Documents\Programing Stuff\Web development\serverRoot\elemukulek\lib\Transphporm\Formatter\StringFormatter.php on line 23

> Warning: DOMDocument::loadXML(): EntityRef: expecting ';' in Entity, line: 3 in C:\Users\admin\OneDrive\Documents\Programing Stuff\Web development\serverRoot\elemukulek\lib\Transphporm\Formatter\StringFormatter.php on line 23

**Comment by TomBZombie** [comment]
I don't think this has anything to do with an iframe, most likely it's a `&` that should be a `&amp;`
