### ISSUE TITLE
+ concatenation

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#59]
The `+` operator doesn't work when using the `data()` function

**Comment by TomBZombie** [comment]
Is this inside the data function e.g. `data("foo" + "bar");` or concatenating with it e.g. `data(foo) + "bar"`

**Comment by solleer** [comment]
`data(foo) + "bar"`

**Comment by TomBZombie** [comment]
I've added a test for this, if it's still not working, please post the exact TSS line you are using.
