### ISSUE TITLE
HTTP Headers

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#6]
In order for Transphporm to act as an entire View layer it needs to be able to supply HTTP headers, and conditional ones at that. Here's how I think it should work at a basic level.

```
//Target the HTML element
html:header[location] {content: '/redirect-here' }

/* or */
html:header[status] {content: '404'; }
```

What this allows us to do is conditionally apply headers:

```
html:data[product=null]:header[status] {content: '404';}
```

Which targets the HTML tag where $data->product is null and then set the status accordingly. This allows for redirects on success and 404/403 errors for other kinds of problems (authorisation denied/ not found/etc). 

Why do this in the TSS? Because otherwise I need another layer that is triggered and contains this logic, adding to the complexity of any view layer.

**Comment by smolinari** [comment]
Hmm....how would the conditional logic be implemented? 

Is there a response object in Level-2? I would have imagined Transphporm would pass its "result" to the response to tell it what to do.

Scott

**Comment by TomBZombie** [comment]
As I said in the post, it would inspect `data` using the pseudo selector for conditional logic :) 

Response is going to be as simple as ` ['headers'  => [], 'body' => string]`

**Comment by smolinari** [comment]
Duh. I read too fast. 

Scott
