### ISSUE TITLE
Data binding

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#60]
This tss
`main { content: template('calendar.xml'); bind: data(model.getData()) }`

gives me the error
> Catchable fatal error: Argument 1 passed to Transphporm\Hook\DataFunction::getData() must be an instance of DOMElement, array given, called in C:\Users\admin\OneDrive\Documents\Programing Stuff\Web development\serverRoot\elemukulek\lib\Transphporm\Parser\Value.php on line 88 and defined in C:\Users\admin\OneDrive\Documents\Programing Stuff\Web development\serverRoot\elemukulek\lib\Transphporm\Hook\DataFunction.php on line 50

**Comment by TomBZombie** [comment]
I believe this was the problem with the `getData()` function. This is now fixed.
