### ISSUE TITLE
HTML entities in XML?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#66]
I'm guessing this is because my HTML is being treated as XML, but how do I correctly use HTML entities or other encoded characters?  Or is this something Transphporm should be handling correctly as is?

Here's an example of the errors I get when I use HTML entities in my template (.xml) file:

Warning: DOMDocument::loadXML(): Entity 'nbsp' not defined in Entity, line: 30 in /Users/chris/disk2/projects/transphporm/vendor/level-2/transphporm/src/Template.php on line 19

Warning: DOMDocument::loadXML(): Entity 'raquo' not defined in Entity, line: 51 in /Users/chris/disk2/projects/transphporm/vendor/level-2/transphporm/src/Template.php on line 19

**Comment by cxj** [comment]
I've found I can explicitly define them without a DTD, as shown below.  This will get rather ugly if I need to define dozens of them.

```
<!DOCTYPE html [
<!ENTITY nbsp   "&#38;#160;">
<!ENTITY copy   "&#38;#169;">
]>
```

**Comment by TomBZombie** [comment]
Yeah, currently Transphporm only supports XML and XML doesn't support HTML entities. The problem is, using the `loadHTML` and `saveHTML` functions in DomDocument, automatically wraps everything in `<html>` and `<body>` tags, breaking partials that don't include these tags.

**Comment by cxj** [comment]
The following almost works. But, I get `]>` as the first 2 characters of output, i.e. appearing at the top, left of my web page.

```
<!DOCTYPE html [
<!ENTITY nbsp   "&#160;">
<!ENTITY copy   "&#169;">
<!ENTITY raquo  "&#187;">
]>
```

**Comment by TomBZombie** [comment]
a better solution will be to have transphporm decode the entities, but it would need to avoid XML entities like &gt; and &amp;.

**Comment by cxj** [comment]
Just to be sure I understand, your reference to `loadHTML` and `saveHTML` is describing why you do _not_ use those commands in Transphporm.  On the one hand, they would correctly handle the HTML entity codes I've got scattered through my existing web pages.  But in Transphporm, they would be a liability since they always wrap their targets in `<html>` and `<body>` tags, which breaks the desired behavior.

**Comment by cxj** [comment]
Entire test XML file:
```
<!DOCTYPE
    html
    [
        <!ENTITY nbsp   "&#160;">
        <!ENTITY copy   "&#169;">
        <!ENTITY raquo  "&#187;">
    ]
>

<html>

    <head>
        <title>Site Map</title>
    </head>

    <body>
        <h1> Some header level 1 </h1>

        <p>Test entity text © »  (copyright and raquote)</p>
        <p>Test encoded text &copy; &raquo;</p>
    </body>

</html>
```

Entire TSS file:
```
h1 {
    content: "My Replaced Title";
}
```

**Comment by cxj** [comment]
It looks like web browsers do not understand DOCTYPE statements in this format adequately.  They ignore everything up to the closing `]>` and then display those 2 characters.  Tested with Safari, Chrome and Firefox.

Meanwhile, the DOCTYPE entity definitions are silencing the XML errors, but doing nothing more than that.

**Comment by cxj** [comment]
Hmm, Wikipedia has this interesting passage (at https://en.wikipedia.org/wiki/Document_type_declaration):  

> Since web browsers are implemented with special-purpose HTML parsers, rather than general-purpose DTD-based parsers, they don't use DTDs and will never access them even if a URL is provided. The DOCTYPE is retained in HTML5 as a "mostly useless, but required" header only to trigger "standards mode" in common browsers.[2]

Mostly useless, but required.  That explains a lot.

**Comment by cxj** [comment]
Browsers apparently don't implement full SGML parsers, so they don't understand the DOCTYPE internal subset, but fail in the above annoying way.   Another passage to that effect from Wikipedia: 

> The last part, surrounded by literal square brackets ([]), is called an internal subset which can be used to add/edit entities or add/edit PUBLIC keyword behaviors.[3] The internal subset is always optional (and sometimes even forbidden within simple SGML profiles, notably those for basic HTML parsers that don't implement a full SGML parser).

I guess I've proven that using DOCTYPE definitions will never be a viable solution.

**Comment by TomBZombie** [comment]
I've fixed this, if the document cannot be loaded as XML, it's loaded as HTML, it's slightly less efficient as DomDocument will wrap HTML partials in `<html>` and `<body>` tags, so the partial has to be extracted. That said, if you enable caching it will remove this negligible performance overhead as it will only happen when the file changes.

However, one caveat for this is that it is converted to XML for output. so `<img src="foo.jpg">` becomes `<img src="foo.jpg" />` in the rendered template and entities are converted `<span>&pound;</span>` is `<span>£</span>`. See the unit tests in the above commit for examples.

**Comment by cxj** [comment]
Maybe this would be a better solution.  It converts HTML entities into the actual characters, which XML is just fine with.  And it avoids collision with XML entities, at least according to the php.net documentation.

`$xml = html_entity_decode($xml, ENT_COMPAT | ENT_HTML5);`

**Comment by TomBZombie** [comment]
Won't that convert `&amp;` to `&` and `&lt;` to `<` ? 

Regardless, it's probably better to fully support HTML including unclosed tags so the commit above is a more robust solution than string replacement on the supplied HTML

**Comment by TomBZombie** [comment]
That said, currently there is zero error reporting when an invalid document is passed, I'll add that in

**Comment by cxj** [comment]
Hm.  My limited test was unfortunately for `&nbsp;`, `&copy;` and `&raquo;` as those were used in my web pages.  Indeed, `&amp;` and `&lt;` cause some odd problems.  Looking into that now.

**Comment by TomBZombie** [comment]
I thought about it some more and can reduce the performance impact. Instead of creating a new Document to load the HTML and then importing it into the original document, it now loads the HTML into the (now only) document and replaces the documentElement `<html>` tag with the `<template>` element for partials. For HTML documents with a `<html>` tag already, it just loads the content into the document.

**Comment by cxj** [comment]
Your latest change is working for me.  Thanks much!

**Comment by Pixelfck** [comment]
Does this also take into account that HTML allows for 'invalid argument syntax' (for example the `readonly` in `<input type="text" name="example" value="" readonly>`)?

The XHTML spec requires such arguments to be written as `readony="readonly"` which is less than nice.

**Comment by TomBZombie** [comment]
Yes, it now uses `DomDocument`'s `loadHTML` function if `loadXML` fails, the `loadHTML` function is incredibly forgiving  and will load even invalid HTML with missing tags/quotes/etc
