### ISSUE TITLE
Version 1.1 - Feature requests

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#67]
I'm going to make a 1.1 release. Along with a lot of bug-fixes there are several new features over 1.0

- #66 - HTML support
- Modularity (needs documentation), you can load modules that register custom:
   - Functions e.g. `content: CUSTOMFUNCTION(args)`
   - Pseudo elements e.g. `td:CUSTOMPSEUDO {content: bar}`
   - Properties e.g. `div { CUSTOMPROPERTY: "foo"; }`
   - Formatters e.g. `div {content: bar; format: CUSTOMFORMATTER}`
- #46 - Template inheritance 
- Single line comments
- #3 - limit on repeat, you can call `repeat: data(list) 3` to only show the first 3 records from `data(list)`
- #53 - Allows @import to reference the `data()` function

Is there anything anyone would like to see for the 1.1 release?

**Comment by Pixelfck** [comment]
I think the main thing I would like to see is extra documentation. Documentation is the deciding factor for people to adopt or reject a library and since *Template animation* is a new concept to many developers out there, documentation needs to be comprehensive.

I think there may even be need for a tutorial or two, although it would be better if some blogger did this for you.

**Comment by solleer** [comment]
Can to ability to create arrays directly in tss be added so for example, if you had groups with different permissions and a few groups could access one page you want to pass a list of those groups to the explicit function testing for membership.

**Comment by TomBZombie** [comment]
Can you give an example of how you'd want this to work? One better method might be a `json` function which parsed a json string:

```php
content: data(model.someFunc(json('["foo", "bar"]'))
```

**Comment by TomBZombie** [comment]
@Pixelfck you're right, of course, I'm going to finish the Wiki pages when I get time and add the new features (above). I think some example pages with HTML forms would help, even some downloadable example projects.

**Comment by solleer** [comment]
I like the idea of a json function. It sounds like the best option with lots of flexibility

**Comment by solleer** [comment]
Could there be something to allow access to what is set as the content of an element

**Comment by TomBZombie** [comment]
It would be possible to have `content()` but how would this work for elements that weren't just text? Would it return the HTML for the content?

**Comment by solleer** [comment]
It could be `text()` which returns all text from children

**Comment by solleer** [comment]
Could a version of `nl2br` be built into the content property somehow. I made a function for transphporm that allows the functionality at https://github.com/solleer/Transphporm-nl2br. The reason you can't just use the native nl2br is because it would require the format to be `html` and that would compromise the built in protection against users injecting their own elements.

**Comment by TomBZombie** [comment]
Ideally this would be `content: data(foo); format: nl2br` which would do what you have there, so implement `formatter` rather than a function for it.

**Comment by solleer** [comment]
That sounds good

**Comment by solleer** [comment]
Is the nl2br format in #97 good

**Comment by solleer** [comment]
Once imports and baseDir being relative to the current imported dir and the cache fixes are done then it is ready for the 1.1 version

**Comment by TomBZombie** [comment]
Yes, caching needs looking at and to do that `Sheet` needs to be changed to use `Tokenzier` and tokens used everywhere. At the moment we have places where strings are used and then tokenized, instead the sheet should be tokenized and tokens passed around instead of strings. This will make caching a little simpler as well as we can cache the tokenized tss and reload that instead of tokenzing different strings throughout the code.

**Comment by solleer** [comment]
I am thinking that the version 1.1 could be released once tokenizer is used everywhere then the next release (1.2 or a 1.1.x) could include the cache fixes

**Comment by solleer** [comment]
Check out the release draft
