### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by smolinari** [Level-2/Transphporm#7]
Wouldn't it be cool, if TSSs data requirements ended up translated to GraphQL as a generic api to the (any) data stack (also internally within PHP)? I mean, this sort of hits on what I was envisioning. 

https://www.youtube.com/watch?v=WQLzZf34FJ8
https://www.youtube.com/watch?v=gY48GW87Feo

Someone already started a PHP version of the PHP Server implementation too. 

https://github.com/webonyx/graphql-php

:sunglasses: 

Scott

**Comment by TomBZombie** [comment]
Interesting idea, I'm not quite sure how you're wanting to tie this in to transphporm though:

How would you envisage this working with Transphporm? 

Most of our data in PHP projects comes from databases, so would you have to take the database result, and then translate that into GraphQL Objects? Can this be done automatically? 

Assuming it can be done automatically, why would you then query the result set rather than just providing those queries to the database?

Would you put Graph Queries in the TSS? It seems to me that most of the time, the query data is going to be coming from $_GET and $_POST. Does this mean you'd need to build the query using string concatenation before running it?

**Comment by smolinari** [comment]
I am always going on the premise that the view always requires or requests the data from the model. It also doesn't matter if I have a view on the server or a view on the client, the request for data is always from the view. The API for the data request (or manipulation) is done through GraphQL. 

I mean, if I have to define the data in the TSS to put in in the right places to "view it", why can't it also be the source for the request for the data too, at the same time?

Scott

**Comment by TomBZombie** [comment]
I agree with the premise, but just taking a simple example. I have `$_POST['id']` and I have a database record to look up with that ID. How do I get to that record using this approach? I don't think there's any way to achieve this using only GraphQL and/or TSS

**Comment by smolinari** [comment]
You have a request for `user/124345` and it would call the view, which would change that into

{
  user(id: 12345) {
    firstname
    lastname
    phone
  }
}

because the TSS says it needs those fields too. 

In other words, the Transphporm view system would only create a proper GraphQL request for the data it needs, based on the page it is requesting.

The GraphQL request would then have to be sent through the type definition converter (I think that was what it was called). After the converter, the business logic would do its thing (the model) and then give back the data to the converter, so it can return the proper GraphQL response, which the view puts together, because it knows how through the TSS definitions. 

Whether or not you transmit the GraphQL request or response over a wire or within the server itself is totally irrelevant and thus, we have a complete view system, that is portable between client and server and is completely standardized. The concept is brilliant.  

And, I am also of the opinion, the view should be found totally on the client side. That is where the web is heading, I believe because it makes the most sense. It is better to only send the data needed, when it is needed and not always with whole HTML pages.  

Scott

**Comment by TomBZombie** [comment]
I get the concept but I'm not sure how it fits into transphporm at all. With transphporm you pass it a data structure (that could easily be a GraphQL response). What I'm not really getting is how we could use Transphporm to generate the GraphQL request, because it needs to know a lot of various things: 

- The GraphQL object
-how to generate the request, what fields (e.g. postdata or data being read from a form field on the page if it's clientside) . 
- When to send the request

Without making a very complex syntax I'm not sure this could be expressed in TSS.

Let's take an example. I type in "Scott" into the search box (which searches for users using IDs or Names), it now needs to perform a query that says: "Find me any record where the name is "Scott" or the id is "Scott"). To express this problem in TSS, is going to be a very complex thing. It would be a lot easier to do this outside TSS and then just pass the response in and have it rendered. Not only that, TSS isn't coupled at all to a particular query language

**Comment by smolinari** [comment]
I think it is because I keep thinking that TSSs are "compiled" into a final view or I rather I think they should. So, the TSS is a meta type definition, but used only once at initialization. When it compiles, it also produces all the glue between the model and view (and even the required behavior in the view), automatically. I guess that isn't what is happening. So, never mind.

Scott

**Comment by TomBZombie** [comment]
I was thinking of it from a purely practical point of view, I just can't see how you'd get from A to B without requiring writing a lot of code in the TSS, which I don't see how you'd express in a nicer way that doing it in PHP or JS before passing the result into tss. I'm not saying it's not possible, but I can't see how it would work.

Whether it's compiled into a view or not doesn't really matter here.

Could you give an example of the code you'd expect to see for my example use-case above, and where that code could go (TSS, Javascript? Somewhere else?)

- The user types "Scott" into a box and presses a button called "Search"
- This triggers an event which generates a GraphQL request
- It sends it off to the (correct!) GraphQL processor and gets the response
- It then renders the template with the retrieved data.

Here's my attempt, using CSS style targets, assume the HTML looks like this

```html

<form>
	<input type="text" name="searchvalue" />
	<input type="submit" name="Submit" />
</form>

<div id="search">


</div>
```

Then we can get a little way there, possibly, by doing something like this:

```css

/* bind a click event to the submit button which sets the target to "search"
I'm thinking this could work like :target in CSS
 */
input[type="submit"]:click {target: "search"}

/* This is only processed when the target is "search" */
/* using the current repeat function, and data() function, also reads the value attribute from the input on the page */
#search:target {repeat: data(model.function, attr(input[name="searchvalue"], value));}

```

However, it's a bit clunky and I'm not sure it's better than just doing it in javascript....and I have no idea how you'd link in GraphQL

**Comment by smolinari** [comment]
Here is an example I just found quickly from here.

http://www.w3schools.com/php/php_ajax_livesearch.asp 

The example would be the final compiled output of a search form.
```
<html>
<head>
<script>
function showResult(str) {
  if (str.length==0) { 
    document.getElementById("livesearch").innerHTML="";
    document.getElementById("livesearch").style.border="0px";
    return;
  }
  if (window.XMLHttpRequest) {
    // code for IE7+, Firefox, Chrome, Opera, Safari
    xmlhttp=new XMLHttpRequest();
  } else {  // code for IE6, IE5
    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
  xmlhttp.onreadystatechange=function() {
    if (xmlhttp.readyState==4 && xmlhttp.status==200) {
      document.getElementById("livesearch").innerHTML=xmlhttp.responseText;
      document.getElementById("livesearch").style.border="1px solid #A5ACB2";
    }
  }
  xmlhttp.open("GET","livesearch.php?q="+str,true);
  xmlhttp.send();
}
</script>
</head>
<body>

<form>
<input type="text" size="30" onkeyup="showResult(this.value)">
<div id="livesearch"></div>
</form>

</body>
</html>
```

But the template XML for the search would be
```
<form>
<input class="livesearch" type="text" size="30">
<div id="livesearch"></div>
</form>

```
and the TSS would be

```
.livesearch input {onkeyup: showResult()}
```
The function `showresult()` is "offered" to the designer by the front-end dev. The designer only knows the function name and what triggers the function. This is also only an example of the possible behavior "glueing". It is also so simple, one would say, "Why not just write that onkeyup in the HTML?" That is a question I can't answer currently. LOL!

And instead of the AJAX with XML, the JS code would send GraphQL requests and operate with the responses. 

Scott

**Comment by TomBZombie** [comment]
That makes sense, but there's nothing really for Transphporm to do here that interacts with GraphQL?

**Comment by smolinari** [comment]
Not directly. Transphporm is only responsible for compiling any prebuilt JS / PHP code necessary to make the GraphQL requests and receive them, but only because they were declared and required by the TSS. 

Transphporm could even use the [introspect feature of GraphQL](https://facebook.github.io/graphql/#sec-Introspection) to help the designer "figure out" what fields she has to work with. For instance, she could simply add this in a TSS.

`.introspect {object: user;}`

compile and then call the page the TSS belongs to. Transphporm would give her all the fields available from the server for the user object. 

or this.

`.introspect {object: user; meta: true; related: true;}`

This would return all fields, all metadata and any related objects with all fields and meta data related to a user object. 

Scott

**Comment by TomBZombie** [comment]
I can see sort of why that would be useful, but it would still tie TSS to a specific data-model implementation. Something I don't want to do.

It might be useful to add a custom formatter for that as part of a different project (e.g. TSS/GQL binding) but it shouldn't be included in the core.

It might be useful to add a general debugging formatter though. e.g. 

```
div {content: data(); format: var_dump; }
```

To display information about the content of the supplied data.
