### ISSUE TITLE
Can this be done, and if so, how?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#75]
My `default.tss` file looks like this:
```
main {
    content: data(__content__);
    format: html;
}

footer nav {
    content: template("footer-nav.xml");
}
```

My `default.xml` file:
```
<!DOCTYPE html>
<html xml:lang="en" lang="en">
    <head>
        <title>Page Title</title>
    </head>

    <body>
        <header>
            <h1>Page Header</h1>
        </header>

        <main>
            Main
        </main>

        <footer>
            <nav>
            </nav>
        </footer>
    </body>
</html>
```

And the `footer-nav.xml` file has:
```
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="/login">Login</a></li>
    <!-- Etc. -->
</ul>
```

As is, it works fine.  Now I want to dynamically add the currently logged in user name (if any) to the footer navigation, i.e. add an element to `footer-nav.xml` above that is something like:
```
<div>
    <user>current username</user>
</div>
```

How do I then set that content from TSS?  

Because the footer section is set via `content: template("footer-nav.xml");` I do not seem to be able to set content inside of it from my `default.tss`.  If it were in `default.tss` instead, I could just use:
```
user {
        content: data(output.auth.getUserName);
}
```
But that does not work here.

**Comment by TomBZombie** [comment]
You should use valid tags, although that won't stop it working. However, the reason this doesn't work is that transphporm orders TSS rules by their length. e.g. if there's a single selector e.g. `div` it will be run before rules with more selectors e.g. `div > span`. Perhaps this should be changed and the order of the file should always be respected.

Changing 

```css
user { ... }
```

to

```css
footer user { ... }
```

ot

```css
footer nav user { ... }
```
will fix it.

**Comment by cxj** [comment]
Thank you very much.  That indeed does fix it.

For some reason, I wrongly jumped to the conclusion that the problem was a restriction on included content, rather than stopping to think about the problem more logically.  This current behavior is how CSS behaves as well, is it not?  Staying parallel with CSS seems like a good idea for TSS.
