### ISSUE TITLE
<!doctype html>

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#8]
Transphporm uses XML, which is fine, but if you try to load a string that starts with `<!doctype html>` it breaks. Using loadHTML sort of avoids the issue (Although this causes it's own errors on HTML5 tags, section, article, etc and you have to suppress the warnings.... which also isn't great)

The problem with loadHTML is that it seems to completely break DomDocument's formatOutput and preserveWhitespace, it just does it's own thing. Is this an issue? Not really, I just quite like seeing the nicely formatted output.

We can't really use saveHTML either because it outputs everything with a doctype, html and body even if it's a HTML fragment so whatever happens we must rewrite the doctype for output.

My preference is keeping with XML: Strip the doctype on input, save it, and then prepend it to the output string.

**Comment by smolinari** [comment]
The question needed to be answered for this is, what will the designer prefer to use? She'll probably want to use HTML to create the page. But, certainly can work with XML as templates.

However, the fact the structure (with data) will need to be "transphpormed" to output with a certain document type declaration is usually accompanied with a piece of logic too. So, in my mind, it is data for the structure and thus a prime abstraction to go into a TSS of a main layout template.  

Saying that, there might also need to be some default TSS supported declarations. For instance,

`document {type: getDocumentType();} `

Any declaration missing "." or "#" and is not a standard HTML tag is a TSS specific declaration.

The `getDocumentType();` can be any method called on the page's general (view?)model, offered to the designer by the back-end developer (or added to the TSS by the backend dev herself). It could be called `retrieveDocumentType()` or `getDocType()`, it doesn't matter. The dev and the designer only have to agree on the fact there is this logic. 

Theoretically, the dev could have also started simply with.......

`document {type: '"-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"`;}` 

.....just to get an output and later the dev could add the method, which changes this output, depending on the user's browser. 

The same can go for content type declarations.

`content {type: 'text/html'; lang:'en';}`

for a multilingual site and later with the necessary logic behind it....

`content {type: 'text/html'; lang: getLanguage();}`

Am I being a rambling idiot again, or is this at all feasible?

Scott

**Comment by TomBZombie** [comment]
After further testing it seem's that PHP's DomDocument is case sensitive, changing `<!doctype>` to `<!DOCTYPE> which is a much easier problem to solve, either we automatically uppercase it, or people have to provide it in uppercase. This is a lot simpler, anyway!

**Comment by smolinari** [comment]
I edited my reply above. I meant selectors not declarations (which a selector is a part of). Transphporm will probably need its own default set of selectors. Theoretically, they could (should) also be extensible too. 

So, if the uppercase version works, what would the TSS selector be to make the doctype dynamic (if wanted)?

To me, like I mentioned above, the doctype is data for the XML structure. So, the designer would not put a ' <doctype>` in the main layout template, but rather in the TSS for that template. So, I still think my suggestion holds merit. 

`document {type: getDocumentType();}`

or even just 

`doc {type: getDocumentType();}`

Scott

**Comment by tontof** [comment]
Changing ```<!doctype>``` to ```<!DOCTYPE>``` does not work:
```PHP Warning:  DOMDocument::loadXML(): StartTag: invalid element name in Entity```
PHP 5.5.9
I need to prepend it to output.

**Comment by TomBZombie** [comment]
This is another one of those problems that exists in the differences between loading strings and loading files. I think perhaps we will have to enforce valid XML in as a string so 

`$xml = '<div> </div> <span> </span>';` will not work and must be `<template> '<div> </div> <span> </span></template>`

**Comment by tontof** [comment]
Well I don't know, but personally  I don't use ```$xml = '<div> </div> <span> </span>';``` and all my xml have a root element. So for me, the modification just sound good :-)

**Comment by TomBZombie** [comment]
This should now be sorted along with #25 Templates are wrapped in `<template>` tags if there is no `<!DOCTYPE` or `<?xml` declaration. If you supply a file/string with a doctype or XML declaration it's treated as an entire document, rather than a partial.
