### ISSUE TITLE
TSS true/false failing

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#80]
This code seems to be failing:
```
<?php
require 'vendor/autoload.php';

$xml = '<h1>Original Title</h1>';

$data = [
    'title'         => 'My Title',
    'isLoggedIn'    => true,
];

$tss = '
    h1:data[isLoggedIn = true] {content: "Title: ", data(title); }
    h1:data[isLoggedIn = false] {content: "No title";}
';


$template = new \Transphporm\Builder($xml, $tss);

echo $template->output($data)->body;
```
Specifically, it's the `data[isLoggedIn = true]` and `data[isLoggedIn = false]` expressions in the TSS which seem to fail.  If I set the value of `isLoggedIn` to a non-zero integer, then it evaluates the `true` branch.  I can compare directly to integers successfully, also, e.g. `data[isLoggedIn = 3]`.

I'm using the latest `@dev` revision:
```
Updating dependencies (including require-dev)
  - Updating level-2/transphporm dev-master (a71e360 => 2c480d5)
    Checking out 2c480d51431be3d9947cce7c59ad61726d32de60
```

**Comment by cxj** [comment]
Ah, the logic test is white space sensitive.
This fails:
```
    h1:data[isLoggedIn = false] {content: "No title";}
```
This works:
```
    h1:data[isLoggedIn=false] {content: "No title";}
```

Is this how it should properly work?

**Comment by TomBZombie** [comment]
Yes, the spaces break the parser currently! No spaces are how the w3 display the CSS syntax for the same thing:

https://www.w3.org/wiki/CSS/Selectors/attribute_selector/attribute~%3Dvalue

**Comment by cxj** [comment]
Silly me, thinking like a programmer, instead of a styling standards committee member.

> This selector represents an element with the "attributename" attribute whose value is a whitespace-separated list of words, one of which is exactly "val".
