### ISSUE TITLE
Repeat when data is from function

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#83]
When the data for a repeat is from a function the data is wrapped messed up so you must use `$value[0][0]` instead of `$value[0]`

**Comment by hobbeshunter** [comment]
Could this be the reason for https://github.com/Level-2/Transphporm/issues/79 too?

**Comment by solleer** [comment]
I thinks so. The confusing thing is sometimes it should be `$value[0]` and other times `$value[0][0]`

**Comment by solleer** [comment]
The problem is that the issue only occurs when the data is from a function. The underlying problem is the way the parser returns the value and how it is given to the properties.

**Comment by TomBZombie** [comment]
Yes, take a look at the new-parser branch.  This is one of the reasons the parser needs updating. I've added some specific tests for the parser too. Unfortunately some of the main tests are still broken but hopefully it should make more sense

**Comment by solleer** [comment]
All of the issues in the tests that involve the parser are because of `\Transphporm\Pseudo\Attribute` when it sends it to the parser and the parser miss evaluates

**Comment by solleer** [comment]
I think the problem is that what is being passes to the parser is like `id="2"` instead of something like `data(id)="2"`

**Comment by solleer** [comment]
can we change the syntax to `:conditional[data(foo())=true]` instead of `:data[foo()=true]`
The issue is that otherwise the tokens must be messed with and the amount of tokens before the equal to sign can change so in order to be the most flexible we should change it to `:conditional`

**Comment by solleer** [comment]
Changing it would allow much simpler code and more variability like `:conditional[data(foo)+iteration(id)=true]`

**Comment by solleer** [comment]
I can change it to `:conditional` I just need to know that it makes sense and is an acceptable change to make

**Comment by solleer** [comment]
Also I noticed that the functions like data and template all have to parse the tokens themselves. Is there a way to allow the function set to parse the tokens before passing them on to the functions so that way if people want to make their own functions, they don't have to remember to parse the tokens.

**Comment by TomBZombie** [comment]
They don't have to parse the tokens, they are given a set of parsed tokens. They do need to loop through the tokens. This is for nesting purposes. `foo(bar('aaa'))`. Feel free to modify it to work differently, however as I mentioned before, there are times when you need the expression inside `data(...)` to be parsed before `data()` is called and times when you need it afterwards. 

> The issue is that otherwise the tokens must be messed with and the amount of tokens before the equal to sign can change so in order to be the most flexible we should chan

You can  send any tokens to `valueParser->parseTokens()` so it shouldn't matter how many there are. The parse() and parseTokens() functions should be able to handle any expression before or after tokenisation

**Comment by solleer** [comment]
So for the json function it will not need to parse the tokens and can just directly use the args given?

What I was saying about messing with the tokens is that it can be done but in order to support future conditionals without having to change the pseudo code it would be best to have it directly evaluate the statement without having to add tokens. Otherwise where do you put the closing bracket token since sometimes the first part is `id` and sometimes it is `foo()` so there is a different amount of tokens to skip ahead there. Additionally sometimes the conditional is just `=` but other times it is `!=` (with more possibly added in the future) so you would have to put the closing bracket token before all conditional parts.

**Comment by solleer** [comment]
When I comment out the first two lines of `run` in the template function where the args are parse, the tests all pass so it seems that they don't need to be reparsed. I understand why the data function does it sense it is using the parsing with the inner contents on its own data. I think this answers my question if things like the json function need to parse their args. I think they do not. So the parsing in the template function can be removed. Correct?

**Comment by solleer** [comment]
The main failure is when using array lookup with tests like `testFilterDataArray`

**Comment by solleer** [comment]
Can you change it to understanding `anArray["test"]` to be the same as `anArray.test`. Right now it interprets open square brackets as only for pseudo and the only reason your attr pseudo doesn't work right now is because you didn't pass it the direct pseudo. With my changes it will change the way that works but I need the array access to be fixed in order for all problems to be fixed. Also support for `true` and `false` needs to be added. That is why the cache test with `data[show=false]` fails because it interprets the false as not a Boolean.

**Comment by solleer** [comment]
Look at #87. All unit tests are passing now 😄 🎉
