### ISSUE TITLE
Magic __get method fails for data()

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#88]
Accessing object properties via the magic `__get()` method does not work.  Note that no exception is thrown, hence I don't think it is even called.  This might be a PHP syntax special case, such as described in this block part way down the PHP Overloading page ([php.net/__get](http://php.net/__get)):

> Note:
The return value of __set() is ignored because of the way PHP processes the assignment operator. Similarly, __get() is never called when chaining assignments together like this:
 $a = $obj->b = 8; 

Can this be made to work?  Is there a variation on calling data() in the TSS that can make it work in the current code?  I tried a few variations, and can call `__get` explicitly via `data(__get)` but don't know how to pass the argument.

```php
<?php
require_once "vendor/autoload.php";

$xml = '<h1>Original Title</h1>';

class Data {
    protected $data = array();
    public    $baz = 'Baz';

    public function __construct() {
        $this->data['foo'] = 'Foo';
        $this->data['bar'] = 'Bar';
    }

    public function __get($name) {
        if (array_key_exists($name, $this->data)) {
            return $this->data[$name];
        }
        throw new Exception("no such property");
    }

    public function getBar() {
        return $this->data['bar'];
    }
}

$output = new Data;

// this fails, using __get magic method.
$tss      = 'h1 {content: data(foo); }';
$template = new \Transphporm\Builder($xml, $tss);
echo $template->output($output)->body . PHP_EOL;

// this works, using explicit method.
$tss      = 'h1 {content: data(getBar); }';
$template = new \Transphporm\Builder($xml, $tss);
echo $template->output($output)->body . PHP_EOL;

// this works, using public property.
$tss      = 'h1 {content: data(baz); }';
$template = new \Transphporm\Builder($xml, $tss);
echo $template->output($output)->body . PHP_EOL;
```

**Comment by solleer** [comment]
When it checks to see if the method exists the check doesn't validate magic methods. I remember when this was removed a while ago. I will see why I requested that support be removed.

**Comment by cxj** [comment]
I grabbed a copy of the new-parser branch and ran my sample above against it.

The magic get of property _foo_ via `data(foo)` stills fails as before, but now the `data(getBar)` calls also fails to return anything.  I'm assuming there is an intentional backward compatibility break in the new parser.

If I change the `data(getBar)` to `data(getBar())`, then it works.  That is an acceptable change.

Interestingly, that also means I can now call `__get()` directly via `data(__get("foo"))` and it works.  It's kind of a hack to do that, but at least there is way to display my object's properties via Transphporm now with the new parser.

**Comment by solleer** [comment]
Correct. With the new parser, function calls must be explicit.

**Comment by cxj** [comment]
Thank you for the responses.  I'd like to see the new parser merged to master.  :)

**Comment by cxj** [comment]
Would still like to see PHP magic methods work, too.

**Comment by solleer** [comment]
I think this may have caused an issue with maphper earlier with magic methods being called at the wrong time

**Comment by solleer** [comment]
I think the problem before was that since functions weren't explicit it would call properties

**Comment by solleer** [comment]
This test passes
```php
public function testDataObjCallMagicMethod() {
	$xml = "
	<div></div>
	";

	$data = new Foo;

	$tss = "div { content: data(testCall()); }";

	$template = new \Transphporm\Builder($xml, $tss);

	$this->assertEquals('<div>test</div>', $template->output($data)->body);
}

class Foo {
	public $model;

	public function __construct() {
		$this->model = new Bar();
	}
	public function getBar($bar) {
		return $bar;
	}

	public function returnFalse() {
		return false;
	}

	public function returnTrue() {
		return true;
	}

	public function returnOne() {
		return 1;
	}

	public function add($a, $b) {
		return $a+$b;
	}

	public function __call($name, $args) {
		if ($name == "testCall") return "test";
		throw new \Exception();
	}
}
```

**Comment by solleer** [comment]
I assume this can be closed

**Comment by cxj** [comment]
I'm not completely sure.  What's the proper syntax to access an object's public property under the new parser?  That is, if I have:
```
    class Foo {
        public $bar = "bar";
    }
    $data = new Foo;
```
How do I write TSS to ask for `$bar` to be used as the content?

**Comment by solleer** [comment]
If foo is being passed as root data then
`data(bar)`

**Comment by cxj** [comment]
Does not work with magic method `__get()`.  I admit it may be impossible, or more difficult than is worth the trouble to make it work.  Here is my test case:

```
<?php

require 'vendor/autoload.php';

class getTest {

    private $data = array('a' => 'a', 1 => 1);

    public function __get($name) {
        echo " >>  Getting property '$name'\n";

        if (array_key_exists($name, $this->data)) {
            return $this->data[$name];
        }

        throw new Exception("no such property");

        return null;
    }
}

$data = new getTest;

$xml = "<div></div>\n";

$tss = "div { content: data(__get('a')); }";        // this works
$tss = "div { content: data(__get(1)); }";          // this works
$tss = "div { content: data(a); }";                 // fails
$tss = "div { content: data(1); }";                 // fails

$template = new \Transphporm\Builder($xml, $tss);

echo $template->output($data)->body;
```

**Comment by solleer** [comment]
The reason `__get` isn't called is because when traversing it uses `isset` to check if the property exists and `isset` doesn't call `__get` it does call `__isset` though

**Comment by cxj** [comment]
Ah!  Thanks!  Adding an `__isset()` magic method to my class makes my test work.  :-)

```php
    public function __isset($name) {
        if (array_key_exists($name, $this->data)) {
            return true;
        }
        return false;
    }
```

**Comment by cxj** [comment]
I just added `__isset()` functions to my production code.  My unit testing passes.  So I think this can be closed now.

**Comment by solleer** [comment]
This should definitely be documented to avoid future confusing.

**Comment by solleer** [comment]
I added some light documentation
