### ISSUE TITLE
Use tokenizer throughout

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#91]
Now we have the tokenizer it doesn't makes sense to use the `BracketMatcher` and `StringExtractor` classes in the `Sheet` class and elsewhere. It would be tidier to use the tokenizer as the parser throughout the project. Currently there is a fair amount of duplication of effort.

**Comment by solleer** [comment]
I agree.

**Comment by TomBZombie** [comment]
This is a step in the right direction and once `sheet` is done, `Tokenizer` shouldn't be needed in most places as there won't be the need to re-tokenize selctors. For example, `Pseudo\Not` currently looks like this:

```php

	public function match($pseudo, \DomElement $element) {
		if (strpos($pseudo, 'not') === 0) {
			
			$tokenizer = new \Transphporm\Parser\Tokenizer($pseudo);
			$tokens = $tokenizer->getTokens();

			$css = explode(',', $tokens[1]['string']);
			$xpath = new \DomXpath($element->ownerDocument);
			return $this->notElement($css, $xpath, $element);
		}
		return true;
	}

	private function notElement($css, $xpath, $element) {
		foreach ($css as $selector) {
			$xpathString = $this->cssToXpath->getXpath($selector);					
			//Find all nodes matched by the expressions in the brackets :not(EXPR)
			foreach ($xpath->query($xpathString) as $matchedElement) {
				//Check to see whether this node was matched by the not query
				if ($element->isSameNode($matchedElement)) return false;
			}
		}
		return true;
	}
```

`$pseudo` is a string like `not(.two)` which is then tokenized. Instead, `CssToXpath` should take tokens and `$pseudo` should be a set of tokens, so `Pseudo\Not` will become

```php
	public function match($pseudo, \DomElement $element) {
		if ($pseudo[0]['value'] === 'not')  {
			$xpath = new \DomXpath($element->ownerDocument);
			return $this->notElement($pseudo, $xpath, $element);
		}
		return true;
	}

	private function notElement($css, $xpath, $element) {
  		$xpathString = $this->cssToXpath->getXpath($pseudo);	

			//Find all nodes matched by the expressions in the brackets :not(EXPR)
			foreach ($xpath->query($xpathString) as $matchedElement) {
				//Check to see whether this node was matched by the not query
				if ($element->isSameNode($matchedElement)) return false;
			}
		
		return true;
	}

```

This will require several changes:

- CssToXPath will now take a set of tokens instead of a CSS string
- Anywhere that currently does string manipulation will also take a set of tokens instead

This should increase performance throughout as the tss file will be tokenized once (also helping with caching) and we shouldn't need `new Tokenizer` anywhere but `Sheet`.

Obviously this is quite a big task but worth it for simplifying a lot of the functions that currently exist.

**Comment by solleer** [comment]
Is there a way to have everything parsed somehow so that every location supports the functions like in pseudo not

**Comment by TomBZombie** [comment]
Possibly not, `Value::ParseTokens` needs to be called at specific times to apply functions to the relevant element. In theory `Value::Parse` will be redundant as tokens will be used in place of strings everywhere. For debugging purposes, the token now also includes the string that was tokenized.

**Comment by solleer** [comment]
it would be nice for the functions to be supported everywhere

**Comment by solleer** [comment]
Somehow allowing the functions everywhere would be awesome because it would allow the most flexibility

**Comment by TomBZombie** [comment]
Tto allow functions anywhere you need `$valueParser->parse($str);` on any `$str` that contains functions. Unfortunately there's no way to do this automatically because  the correct element won't be set in `FunctionSet` so `iteration()` might not resolve to the correct piece of data.

**Comment by solleer** [comment]
Right now I am trying to have property hook parse all rules before running them because it would allow things like format and content-mode to be set by functions (on a side note, it will take some changing of layout for update-frequency to be parsed). The main problem with parsing tokens beforehand is that if something like `repeat` or `bind` is used then even with the correct element the data changing hasn't occurred before the parsing. If you have any ideas on how to allow the tokens to be parsed ahead of time let me know so I can work on it faster.

**Comment by solleer** [comment]
Sheet parse now uses tokens but it definitely needs to be optimized.
I am thinking that there needs to be a Token object to package some functions together like the `splitOnToken` func in CssToXpath and Sheet. Tell me what you think.

**Comment by solleer** [comment]
The `processAttr` func in CssToXpath also needs to be improved so that it automatically can support any operators that the value parser does

**Comment by TomBZombie** [comment]
Here's how I started it:

```php
	public function parse($pos = 0, $rules = [], $indexStart = 0) {
		$tokenizer = new Tokenizer($this->tss);
		$tokens = $tokenizer->getTokens();

		$rules = [
			['css' => []],
		];

		$i = 0;

		foreach ($tokens as $token) {
			if ($token['type'] === Tokenizer::OPEN_BRACE) {
				$rules[$i]['rules'] = $token['value'];
				$i++;
				$rules[$i] = ['css' => []];
			}
			else {
				//Ignore whitespace at the start of a CSS rule
				if ($token['type'] == Tokenizer::WHITESPACE && count($rules[$i]['css']) == 0) continue;
				//Keep building the CSS rule but ignore duplicate whitespace
				if ($token['type'] == Tokenizer::WHITESPACE && end($rules[$i]['css'])['type'] == Tokenizer::WHITESPACE) continue;
				$rules[$i]['css'][] = $token;
			}
		}

		foreach ($rules as $rule) {
			$this->xPath->getXpath($rule['css']);
		}
```

and then I made `getXpath` take tokens instead of a string, I'll take a look and see what you did  :)

**Comment by solleer** [comment]
I don't know which method I like more

**Comment by solleer** [comment]
I am working on the `attr` function working like `data` so that for the CssToXpath `processAttr` it can just wrap the whole thing in a function and call it.
Here is what I changed `TSSFunction\Attr` to
```php
class Attr implements \Transphporm\TSSFunction {
	private $functionSet;

	public function __construct(\Transphporm\FunctionSet $functionSet) {
		$this->functionSet = $functionSet;
	}

	public function run(array $args, \DomElement $element) {

        $attributes = array();
        foreach($element->attributes as $attribute_name => $attribute_node) {
            $attributes[$attribute_name] = $attribute_node->nodeValue;
        }

        var_dump($attributes);

        $parser = new \Transphporm\Parser\Value($this->functionSet, true);
		$return = $parser->parseTokens($args, $attributes);
        var_dump($return);echo "test1";
		return $return[0];
	}
}
```
The only issue is that `attr("attribute")` doesn't work but `attr(attribute)` does. This would be a BC break if implemented. I don't know a better way to do this.

**Comment by solleer** [comment]
Check out the new commit. I was able to do it without changing the `attr` function. I just added what I was going to do above into the `proccessAttr` in CssToXpath.

**Comment by solleer** [comment]
@TomBZombie What do you think about my sheet parse function? Also what are your thoughts on having a Token or Tokens object to package functions like `splitOnToken` and `removeWhitespace`. The object would probably take a tokens array in its constructor. I don't know if the object would completely replace all the spots we use an array or what but the `splitOnToken` func definently needs to be moved out of sheet and csstoxpath

**Comment by TomBZombie** [comment]
There's not much in it and you completed that first, good job :) Yes the splitOnToken function needs to be moved to its own class along with other token functions. Perhaps tokens needs to be a class with an API like this

```php
//Loop through from the first whitespace char until the next open brace
foreach ($tokens->from(Tokenzier::WHITESPACE)->to(Tokenizer::OPEN_BRACE)) {
	
}

//Get the next token and move the cursor on one
$token = $tokenizer->next();

//Ignore whitespace when looping
$tokenizer->ignoreWhitespace(true);

```
$tokens would be an iterator and the `from` and `to` functions would let you set start/stop points.  The code above would loop from the first Whitepace token until the following opening brace. Omitting from or to would set it to the start/end.

Obviously where $token['value'] is an array of tokens it would also need to be a one of these iterators.

**Comment by solleer** [comment]
Sounds great.
Also you have
```
//Get the next token and move the cursor on one
$token = $tokenizer->next();

//Ignore whitespace when looping
$tokenizer->ignoreWhitespace(true);
```
Did you mean
```
//Get the next token and move the cursor on one
$token = $tokens->next();

//Ignore whitespace when looping
$tokens->ignoreWhitespace(true);
```

**Comment by TomBZombie** [comment]
yes, I did edit it but obviously not fast enough!

**Comment by solleer** [comment]
Should the new class be under parser or not, so `Transphporm\Parser\Tokens` or `Transphporm\Tokens`

**Comment by TomBZombie** [comment]
It's part of the Parser really so I'd put it under Transphporm\Parser

**Comment by solleer** [comment]
This is the class so far
```php
<?php
/* @description     Transformation Style Sheets - Revolutionising PHP templating    *
 * @author          Tom Butler tom@r.je                                             *
 * @copyright       2015 Tom Butler <tom@r.je> | https://r.je/                      *
 * @license         http://www.opensource.org/licenses/bsd-license.php  BSD License *
 * @version         1.0                                                             */
namespace Transphporm\Parser;
class Tokens implements Iterator, ArrayAccess {
    private $tokens;
    private $iterator = 0;
    private $ignoreWhitespace = false;

    public function __construct(array $tokens) {
        $this->tokens = $tokens;
    }

    // Iterator Functions
    public function current() {
        return $this->tokens[$this->iterator];
    }

    public function key() {
        return $this->iterator;
    }

    public function next() {
        if ($this->ignoreWhitespace) {
            do {
                ++$this->iterator;
            }
            while ($this->tokens[$this->iterator]['type'] === Tokenizer::WHITESPACE);
        }
        else ++$this->iterator;
	}

	public function valid() {
        if ($this->ignoreWhitespace) return isset($this->tokens[$this->iterator]) && $this->tokens[$this->iterator]['type'] !== Tokenizer::WHITESPACE;
		return isset($this->tokens[$this->iterator]);
	}

	public function rewind() {
		$this->iterator = 0;
	}

    // ArrayAccess Functions
    public function offsetSet($offset, $value) {
        if (is_null($offset)) {
            $this->tokens[] = $value;
        } else {
            $this->tokens[$offset] = $value;
        }
    }

    public function offsetExists($offset) {
        return isset($this->tokens[$offset]);
    }

    public function offsetUnset($offset) {
        unset($this->tokens[$offset]);
    }

    public function offsetGet($offset) {
        return isset($this->tokens[$offset]) ? $this->tokens[$offset] : null;
    }

    // Helpful Functions
    public function ignoreWhitespace($ignore = false) {
        $this->ignoreWhitespace = $ignore;
    }

    private function getKeyOfTokenType($tokenType) {
        return array_search($tokenType, array_column($this->tokens, 'type'));
    }

    public function from($tokenType, $inclusive = true) {
        $key = $this->getKeyOfTokenType($tokenType);
        if ($inclusive) $key++;
        return new Tokens(array_slice($this->tokens, $key));
    }

    public function to($tokenType, $inclusive = true) {
        $key = $this->getKeyOfTokenType($tokenType);
        if ($inclusive) $key--;
        return new Tokens(array_slice($this->tokens, 0, $key));
    }

    public function splitOnToken($tokenType) {
        $splitTokens = [];
		$i = 0;
		foreach ($this->tokens as $token) {
			if ($token['type'] === $splitOn) $i++;
			else $splitTokens[$i][] = $token;
		}
        return array_map(function ($tokens) {
            return new Tokens($tokens);
        }, $splitTokens);
		//return $splitTokens;
    }

    public function trim() {
        $tokens = $this->tokens;
        // Remove end whitespace
        while (end($tokens)['type'] === Tokenizer::WHITESPACE) {
            array_pop($tokens);
        }
        // Remove begining whitespace
        while ($tokens[0]['type'] === Tokenizer::WHITESPACE) {
            array_shift($tokens);
        }
        return new Tokens($tokens);
    }
}
```
I get this error though
> Parse error: syntax error, unexpected 'implements┬áIterator' (T_STRING), expecting '{'

**Comment by solleer** [comment]
Nevermind I fixed it

**Comment by solleer** [comment]
I can't quite figure out how to have it work well

**Comment by solleer** [comment]
Check out the token-class branch. Its definitely a work in progress. I might need some help with it. Right now I have it break encapsulation so that some tests pass.

**Comment by solleer** [comment]
@TomBZombie What do you think about the tokens-class branch? It is a bit better now but it has issues and it seems to have a bit too many methods.

**Comment by TomBZombie** [comment]
It does look a bit busy to me, but that's due to it implementing iterator and arrayaccess. Are they both really necessary or would specific methods be better?

One thing I would change is this function:


```php

    public function ignoreWhitespace($ignore = false) {
        $this->ignoreWhitespace = $ignore;
    }

```

Because we pass around $tokens in a lot of places, there's potential for action-at-distance. Calling this method on the object somewhere could affect somewhere else that has reference to the same tokens. I don't think it's likely but could occasionally cause odd bugs where doing operations in different orders will have completely different results.

I'd suggest changing it to:

```
    public function ignoreWhitespace($ignore = false) {
        $tokens = new Tokens($this->tokens);
        $tokens->ignoreWhitespace = $ignore;
        return $tokens;
    }

```

and using the return value wherever it's used.

**Comment by TomBZombie** [comment]
I'm trying to remove `getTokens()` from the class. There's no reason we should need to expose the tokens from it directly.

Firstly I'm working on `Sheet::getProperties()` and have this:

```php
	private function getProperties($tokens) {
		$rules = $tokens->ignoreWhiteSpace(true)->splitOnToken(Tokenizer::SEMI_COLON);
		//var_dump($rules);
		$return = [];
		foreach ($rules as $rule) {
			$name = $rule->from(Tokenizer::NAME, true)->to(Tokenizer::COLON)[0]['value'];
			$return[$name] = $rule->from(Tokenizer::COLON)->getTokens();
		}
		return $return;
	}
```

Which is better, but obviously the return value should just be a tokens object. However, this breaks some tests and I can't quite figure out why. It seems to be doing the same as before.

**Comment by TomBZombie** [comment]
@solleer  take a look at the updates and let me know what you think, if you're happy with that I'll move this branch to master and release it as 1.1.

**Comment by solleer** [comment]
Looks great.
