### ISSUE TITLE
Access root data

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#94]
Can something be added to access root data from anywhere.
I have this in `layout.tss`
```
[data-user="all"]:data[request.session("user_id")=false]:header[location] { display: none; }
```
I require `layout.tss` at the end of almost every tss file
I encounter a problem when data has been bound to an element above one with `data-user="all"`
One way to access the root data always would be for data to accept a second parameter and if it is true then it traverses the root data

**Comment by solleer** [comment]
Also could something like `:condition[]` or `:condit[]` replace `data[]`, etc. because it would allow the multiple arguments to be used.
Or instead of the second parameter, a `root()` function could be added which would be `data()` where it always traverses from root data

**Comment by TomBZombie** [comment]
I think either `root()` or `parent()` is the best option here. Whether it's better to count up from the current depth or via `parent()` or down from `root()` is debatable but I think that's the simplest extension

**Comment by solleer** [comment]
Root would probably be better since you always should know what the initial data was

**Comment by solleer** [comment]
could something like `conditional[]` be added to replace `data()`, etc. too.
For instance I have
```
#year option:iteration[=data(year)]:attr(selected) { content: 'selected'; }
```
This works but is very ugly to see and would make more sense if it looked like
```
#year option:conditional[iteration()=data(year)]:attr(selected) { content: 'selected'; }
```

**Comment by solleer** [comment]
So what do you think about the conditional pseudo
