### ISSUE TITLE
File path when using @import

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#98]
I have this in `layout.tss`
```
footer div:nth-child(1):data[request.session("user_id")] {
    content: template("../Modules/user/view/user_nax.xml", ".signedIn");
}
```
The directory prepended to the file path is the one for the tss using import to load layout.tss
This is expected behavior
Could it be changed to if the baseDir is needed in an @import file then it uses the @import file's dir within the file being imported

**Comment by solleer** [comment]
This would require the imported tss rules to be executed separately

**Comment by solleer** [comment]
Since right now all file paths are relative to the main tss then if you use a template in an imported tss file then the file path for the template is relative to the tss file including it which doesn't make since

**Comment by TomBZombie** [comment]
This can easily be fixed for imports in `Sheet.php`:

```php

	private function import($args, $indexStart) {
		if (is_file(trim($args,'\'" '))) $fileName = trim($args,'\'" ');
		else $fileName = $this->valueParser->parse($args)[0];

		$sheet = new Sheet(file_get_contents($this->baseDir . $fileName), pathinfo($this->baseDir . $fileName)['dirname'], $this->xPath, $this->valueParser);
		return $sheet->parse(0, [], $indexStart);
	}
```

Which will move the baseDir used by imported sheets, however it will only affect `@import` and not `template()` calls. I'll look into fixing that but I'm not sure how simple that will be.

**Comment by solleer** [comment]
So how will this be fixed
