### ISSUE TITLE
Pseudo attribute on raw iteration or data

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#99]
This gives me errors with the updated code
```
#year option { repeat: data(year_select); content: iteration(); }
#year option:attr(value) { content: iteration(); }

#year option:iteration[=data(year)]:attr(selected) { content: 'selected'; }
```
It is caused by the last line because the parser doesn't interpret it like a blank iteration call

**Comment by TomBZombie** [comment]
Won't this do the same thing?
```
#year option[iteration()=data(year)]:attr(selected) { content: 'selected'; }
```

If not, I think that's the more sensible way to handle this.

**Comment by solleer** [comment]
With your example you just need to add a colon for it to work
```
#year option:[iteration()=data(year)]:attr(selected) { content: 'selected'; }
```
I like doing that
Its like the `:conditional` pseudo I want but shorter since you just need the `:`
That's great

**Comment by solleer** [comment]
Also check out #100
